import type { BurgerShopRecipe } from './types'

const white = [[1, 1, 1, 1]]
const lime = [[0.213, 1, 0, 1]]
const limeToYellow = [
  [0.213, 1, 0, 1],
  [0.992, 1, 0.448, 1],
]
const limeToMint = [
  [0.213, 1, 0, 1],
  [0.884, 1, 0.873, 1],
]
const limeToWhite = [
  [0.213, 1, 0, 1],
  [1, 1, 1, 1],
]
const confetti = [
  [1, 0, 0.522, 1],
  [0.914, 1, 0, 1],
  [0.179, 0.83, 0.035, 1],
  [0, 0.91, 1, 1],
  [1, 0.501, 0.193, 1],
  [0.831, 0, 1, 1],
]
const gold = [[1, 0.737, 0, 1]]
const trailGold = [
  [0.943, 0.593, 0.174, 1],
  [0.914, 1, 0, 1],
  [1, 0.898, 0.412, 1],
]

const constant = (value: number) => ({ min: value, max: value })
const range = (min: number, max: number) => ({ min, max })
const unityUp: [number, number, number] = [-90, 0, 0]
const popIn = [
  { t: 0, v: 0 },
  { t: 0.115, v: 1 },
  { t: 0.256, v: 0.6 },
  { t: 0.361, v: 0.94 },
  { t: 0.819, v: 0.78 },
  { t: 0.928, v: 0.68 },
  { t: 1, v: 0.13 },
]
const starPop = [
  { t: 0, v: 0 },
  { t: 0.115, v: 1 },
  { t: 1, v: 0 },
]
const twinkle = [
  { t: 0, v: 1 },
  { t: 0.15, v: 0.6 },
  { t: 0.3, v: 0.97 },
  { t: 0.35, v: 0.64 },
  { t: 0.46, v: 0.92 },
  { t: 0.55, v: 0.64 },
  { t: 0.69, v: 0.95 },
  { t: 0.76, v: 0.39 },
  { t: 1, v: 0 },
]
const expand = [
  { t: 0, v: 0.12 },
  { t: 1, v: 1 },
]
const shrink = [
  { t: 0, v: 1 },
  { t: 1, v: 0 },
]

export const burgerShopFootsteps: BurgerShopRecipe = {
  id: 'character-footsteps',
  label: 'Character footsteps',
  unityPrefab: 'FX_Character_FootSteps_01',
  duration: 5,
  looping: true,
  emitters: [
    {
      name: 'Dust',
      texture: 'poof-02',
      sheet: { columns: 4, rows: 3 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 5,
      looping: true,
      life: constant(0.75),
      speed: constant(-1),
      size: range(1.25, 2.25),
      gravity: 0,
      rate: 0,
      rateOverDistance: 2,
      shape: { kind: 'sphere', radius: 0.0001 },
      sizeCurve: shrink,
      color: white,
      localEuler: unityUp,
    },
  ],
}

export const burgerShopCharacterUpgrade: BurgerShopRecipe = {
  id: 'character-upgrade',
  label: 'Character upgrade',
  unityPrefab: 'FX_Character_Upgrade_01',
  duration: 2,
  looping: false,
  emitters: [
    {
      name: 'Sparkles',
      texture: 'sparkle',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 0.5,
      looping: false,
      delay: 0.15,
      life: range(0.35, 0.7),
      speed: constant(0),
      size: range(0.75, 2),
      gravity: 0,
      rate: 0,
      burst: constant(5),
      shape: { kind: 'hemisphere', radius: 1.75 },
      sizeCurve: twinkle,
      color: limeToYellow,
      localEuler: unityUp,
    },
    {
      name: 'Trail',
      texture: 'mask-01',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'additive',
      duration: 2,
      looping: false,
      life: range(0.45, 0.75),
      speed: range(12, 28),
      size: constant(0),
      gravity: 0,
      rate: 0,
      burst: constant(7),
      shape: { kind: 'cone', angle: 0, radius: 1.4 },
      rotateOverLife: true,
      trailLife: 0.5,
      sizeCurve: shrink,
      color: confetti,
      localEuler: unityUp,
    },
    {
      name: 'Upgrade',
      texture: 'sign',
      sheet: { columns: 1, rows: 1 },
      billboard: 'vertical',
      blend: 'cutout',
      duration: 2,
      looping: false,
      life: constant(0.75),
      speed: constant(26),
      size: constant(5),
      gravity: 0,
      rate: 0,
      burst: constant(1),
      shape: { kind: 'point' },
      sizeCurve: popIn,
      color: lime,
      localEuler: unityUp,
      localPosition: [0, 2.42, 0],
    },
  ],
}

export const burgerShopConfetti01: BurgerShopRecipe = {
  id: 'confetti-01',
  label: 'Confetti cone',
  unityPrefab: 'FX_Confetti_01',
  duration: 2,
  looping: false,
  emitters: [
    {
      name: 'Confetti',
      texture: 'confetti',
      sheet: { columns: 2, rows: 2 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 2,
      looping: false,
      life: range(0.85, 1.75),
      speed: range(6, 10),
      size: range(1, 1.75),
      gravity: 0,
      rate: 0,
      burst: constant(25),
      shape: { kind: 'cone', angle: 20, radius: 0.75 },
      sizeCurve: shrink,
      rotateOverLife: true,
      color: confetti,
      localEuler: unityUp,
    },
    {
      name: 'Trail',
      texture: 'mask-01',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'additive',
      duration: 2,
      looping: false,
      life: range(0.9, 1.2),
      speed: range(11, 16),
      size: constant(0),
      gravity: 0,
      rate: 0,
      burst: constant(7),
      shape: { kind: 'cone', angle: 22, radius: 0.5 },
      rotateOverLife: true,
      trailLife: 0.5,
      sizeCurve: shrink,
      color: confetti,
      localEuler: unityUp,
    },
    {
      name: 'Shockwave',
      texture: 'ring',
      sheet: { columns: 1, rows: 1 },
      billboard: 'horizontal',
      blend: 'cutout',
      duration: 2,
      looping: false,
      life: constant(0.4),
      speed: constant(0),
      size: constant(8),
      gravity: 0,
      rate: 0,
      burst: constant(1),
      shape: { kind: 'point' },
      sizeCurve: expand,
      color: white,
      localEuler: unityUp,
    },
  ],
}

export const burgerShopConfetti02: BurgerShopRecipe = {
  id: 'confetti-02',
  label: 'Confetti explosion',
  unityPrefab: 'FX_Confetti_02',
  duration: 2,
  looping: false,
  emitters: [
    {
      name: 'ConfettiExplosion',
      texture: 'confetti',
      sheet: { columns: 2, rows: 2 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 2,
      looping: false,
      life: range(0.85, 1.75),
      speed: range(4, 6),
      size: range(0.65, 1),
      gravity: 0,
      rate: 0,
      burst: constant(25),
      shape: { kind: 'sphere', radius: 0.0001 },
      sizeCurve: [
        { t: 0, v: 1 },
        { t: 0.72, v: 0.9 },
        { t: 1, v: 0.15 },
      ],
      rotateOverLife: true,
      startRotation: { min: 0, max: Math.PI * 2 },
      color: confetti,
    },
    {
      name: 'Trail',
      texture: 'mask-01',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'additive',
      duration: 2,
      looping: false,
      life: range(0.9, 1.2),
      speed: range(11, 16),
      size: constant(0),
      gravity: 0,
      rate: 0,
      burst: constant(4),
      shape: { kind: 'cone', angle: 22, radius: 0.5 },
      rotateOverLife: true,
      trailLife: 0.5,
      sizeCurve: shrink,
      color: confetti,
      localEuler: unityUp,
    },
    {
      name: 'Shockwave',
      texture: 'ring',
      sheet: { columns: 1, rows: 1 },
      billboard: 'horizontal',
      blend: 'cutout',
      duration: 2,
      looping: false,
      life: constant(0.4),
      speed: constant(0),
      size: constant(8),
      gravity: 0,
      rate: 0,
      burst: constant(1),
      shape: { kind: 'point' },
      sizeCurve: expand,
      color: white,
      localEuler: unityUp,
    },
  ],
}

export const burgerShopEating: BurgerShopRecipe = {
  id: 'eating',
  label: 'Eating scraps',
  unityPrefab: 'FX_Eating_01',
  duration: 0.8,
  looping: false,
  emitters: [
    {
      name: 'FoodParticles_01',
      texture: 'food-scraps',
      sheet: { columns: 2, rows: 2 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 0.8,
      looping: false,
      life: range(0.2, 0.4),
      speed: range(5, 12),
      size: range(0.15, 0.4),
      gravity: 5,
      rate: 0,
      burst: range(1, 2),
      shape: { kind: 'cone', angle: 7, radius: 0.35 },
      sizeCurve: shrink,
      startRotation: { min: 0, max: Math.PI * 2 },
      color: white,
      localEuler: unityUp,
      localPosition: [0, 0, 0.35],
    },
    {
      name: 'FoodParticles_02',
      texture: 'food-scraps',
      sheet: { columns: 2, rows: 2 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 0.8,
      looping: false,
      life: range(0.2, 0.4),
      speed: range(5, 12),
      size: range(0.15, 0.4),
      gravity: 5,
      rate: 0,
      burst: range(1, 2),
      shape: { kind: 'cone', angle: 7, radius: 0.35 },
      sizeCurve: shrink,
      startRotation: { min: 0, max: Math.PI * 2 },
      color: white,
      localEuler: unityUp,
      localPosition: [0, 0, -0.35],
    },
  ],
}

export const burgerShopFlies: BurgerShopRecipe = {
  id: 'flies',
  label: 'Flies',
  unityPrefab: 'FX_Flies_01',
  duration: 2,
  looping: true,
  emitters: [
    {
      name: 'Flies',
      texture: 'flies',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 2,
      looping: true,
      life: range(1, 2),
      speed: constant(0),
      size: range(0.4, 0.8),
      gravity: 0,
      rate: 2,
      burst: constant(0),
      shape: { kind: 'sphere', radius: 1.2 },
      noise: range(0.5, 2),
      color: white,
      localEuler: unityUp,
      localPosition: [0, 1.8, 0],
      minHeight: 0.8,
    },
  ],
}

export const burgerShopPoof01: BurgerShopRecipe = {
  id: 'poof-01',
  label: 'Poof',
  unityPrefab: 'FX_Poof_01',
  duration: 2,
  looping: false,
  emitters: [
    {
      name: 'Shockwave',
      texture: 'ring',
      sheet: { columns: 1, rows: 1 },
      billboard: 'horizontal',
      blend: 'cutout',
      duration: 2,
      looping: false,
      life: constant(0.35),
      speed: constant(0),
      size: constant(7),
      gravity: 0,
      rate: 0,
      burst: constant(1),
      shape: { kind: 'point' },
      sizeCurve: expand,
      color: white,
      localEuler: unityUp,
    },
    {
      name: 'Poof',
      texture: 'poof-01',
      sheet: { columns: 4, rows: 3 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 2,
      looping: false,
      life: range(0.35, 0.9),
      speed: range(0.5, 2),
      size: range(3, 6),
      gravity: 0,
      rate: 0,
      burst: constant(5),
      shape: { kind: 'cone', angle: 0, radius: 2 },
      color: white,
      localEuler: unityUp,
    },
  ],
}

export const burgerShopPoof02: BurgerShopRecipe = {
  id: 'poof-02',
  label: 'Poof large',
  unityPrefab: 'FX_Poof_02',
  duration: 2,
  looping: false,
  emitters: [
    {
      name: 'Shockwave',
      texture: 'ring',
      sheet: { columns: 1, rows: 1 },
      billboard: 'horizontal',
      blend: 'cutout',
      duration: 2,
      looping: false,
      life: constant(0.35),
      speed: constant(0),
      size: constant(7),
      gravity: 0,
      rate: 0,
      burst: constant(1),
      shape: { kind: 'point' },
      sizeCurve: expand,
      color: white,
      localEuler: unityUp,
    },
    {
      name: 'Poof',
      texture: 'poof-02',
      sheet: { columns: 4, rows: 3 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 2,
      looping: false,
      life: constant(0.52),
      speed: constant(0),
      size: constant(8),
      gravity: 0,
      rate: 0,
      burst: constant(1),
      shape: { kind: 'point' },
      color: white,
      localEuler: unityUp,
      localPosition: [0, 1.27, -0.36],
    },
    {
      name: 'Poof_small',
      texture: 'poof-02',
      sheet: { columns: 4, rows: 3 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 2,
      looping: false,
      life: constant(0.45),
      speed: constant(0),
      size: constant(4),
      gravity: 0,
      rate: 0,
      burst: constant(1),
      shape: { kind: 'point' },
      color: white,
      localEuler: unityUp,
      localPosition: [0, 1.27, 0],
    },
  ],
}

export const burgerShopSmoke: BurgerShopRecipe = {
  id: 'smoke',
  label: 'Grill smoke',
  unityPrefab: 'FX_Smoke_01',
  duration: 6.83,
  looping: true,
  emitters: [
    {
      name: 'Smoke',
      texture: 'smoke',
      sheet: { columns: 4, rows: 3 },
      billboard: 'vertical',
      blend: 'cutout',
      duration: 0.8,
      looping: true,
      life: constant(0.8),
      speed: constant(0),
      size: constant(6),
      gravity: 0,
      rate: 0,
      burst: constant(1),
      shape: { kind: 'point' },
      color: white,
      localEuler: unityUp,
      localPosition: [0, 2.2, -0.36],
    },
    {
      name: 'Poof_small',
      texture: 'poof-02',
      sheet: { columns: 4, rows: 3 },
      billboard: 'vertical',
      blend: 'cutout',
      duration: 1,
      looping: true,
      life: range(1, 1.4),
      speed: range(0.2, 1.75),
      size: range(1, 2),
      gravity: 0,
      rate: 3,
      burst: constant(1),
      shape: { kind: 'cone', angle: 0, radius: 0.85 },
      color: white,
      localEuler: unityUp,
      localPosition: [0, 0.42, 0],
    },
  ],
}

export const burgerShopSunshine: BurgerShopRecipe = {
  id: 'sunshine',
  label: 'Sunshine',
  unityPrefab: 'FX_Sunshine_01',
  duration: 3,
  looping: false,
  emitters: [
    {
      name: 'Sunshine_01',
      texture: 'sunshine',
      sheet: { columns: 1, rows: 1 },
      billboard: 'mesh',
      blend: 'additive',
      duration: 3,
      looping: false,
      life: constant(1.5),
      speed: constant(0),
      size: constant(18),
      gravity: 0,
      rate: 0,
      burst: constant(4),
      shape: { kind: 'point' },
      sizeCurve: expand,
      rotateOverLife: true,
      color: gold,
      localEuler: [0, 0, 0],
    },
    {
      name: 'Sunshine_02',
      texture: 'sunshine',
      sheet: { columns: 1, rows: 1 },
      billboard: 'mesh',
      blend: 'additive',
      duration: 3,
      looping: false,
      life: constant(1.5),
      speed: constant(0),
      size: constant(18),
      gravity: 0,
      rate: 0,
      burst: constant(4),
      shape: { kind: 'point' },
      sizeCurve: expand,
      rotateOverLife: true,
      color: gold,
      localEuler: [0, 0, 0],
    },
  ],
}

export const burgerShopTableFirstPurchase: BurgerShopRecipe = {
  id: 'table-first-purchase',
  label: 'Table first purchase',
  unityPrefab: 'FX_Table_Station_First_Purchase_01',
  duration: 2,
  looping: false,
  emitters: [
    {
      name: 'Star_rate',
      texture: 'star-02',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 0.5,
      looping: false,
      life: range(0.35, 0.9),
      speed: range(8, 22),
      size: range(1, 2),
      gravity: 0,
      rate: 10,
      burst: constant(0),
      shape: { kind: 'cone', angle: 0, radius: 0.8 },
      sizeCurve: starPop,
      rotateOverLife: true,
      color: limeToWhite,
      localEuler: unityUp,
    },
    {
      name: 'Sparkles',
      texture: 'sparkle',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 0.5,
      looping: false,
      life: range(0.35, 0.9),
      speed: constant(0),
      size: range(1, 1.5),
      gravity: 0,
      rate: 9,
      burst: constant(3),
      shape: { kind: 'hemisphere', radius: 2 },
      sizeCurve: twinkle,
      color: limeToMint,
      localEuler: unityUp,
    },
    {
      name: 'Trail',
      texture: 'mask-01',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'additive',
      duration: 2,
      looping: false,
      life: range(0.3, 0.5),
      speed: range(12, 25),
      size: constant(0),
      gravity: 0,
      rate: 0,
      burst: constant(4),
      shape: { kind: 'cone', angle: 0, radius: 2 },
      trailLife: 0.5,
      color: confetti,
      localEuler: unityUp,
    },
    {
      name: 'Star_burst',
      texture: 'star-02',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 2,
      looping: false,
      life: range(0.35, 0.9),
      speed: range(15, 22),
      size: range(0.75, 1.2),
      gravity: 0,
      rate: 0,
      burst: constant(3),
      shape: { kind: 'cone', angle: 0, radius: 0.8 },
      sizeCurve: starPop,
      rotateOverLife: true,
      color: limeToWhite,
      localEuler: unityUp,
    },
  ],
}

export const burgerShopTableUpgrade: BurgerShopRecipe = {
  id: 'table-upgrade',
  label: 'Table upgrade',
  unityPrefab: 'FX_Table_Station_Upgrade_01',
  duration: 2,
  looping: false,
  emitters: [
    {
      name: 'Star_rate',
      texture: 'star-02',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 0.5,
      looping: false,
      life: range(0.35, 0.9),
      speed: range(8, 22),
      size: range(1.25, 2.25),
      gravity: 0,
      rate: 10,
      burst: constant(0),
      shape: { kind: 'cone', angle: 0, radius: 2 },
      sizeCurve: starPop,
      rotateOverLife: true,
      color: limeToWhite,
      localEuler: unityUp,
    },
    {
      name: 'Dots',
      texture: 'glow',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'additive',
      duration: 0.5,
      looping: false,
      life: range(0.35, 0.9),
      speed: constant(0),
      size: range(0.5, 0.75),
      gravity: 0,
      rate: 9,
      burst: constant(3),
      shape: { kind: 'hemisphere', radius: 1.5 },
      sizeCurve: twinkle,
      color: limeToMint,
      localEuler: unityUp,
    },
    {
      name: 'Trail',
      texture: 'glow',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'additive',
      duration: 2,
      looping: false,
      life: range(0.5, 0.8),
      speed: range(3, 9),
      size: constant(0),
      gravity: 0,
      rate: 0,
      burst: constant(3),
      shape: { kind: 'cone', angle: 0, radius: 2 },
      trailLife: 0.28,
      color: trailGold,
      localEuler: unityUp,
    },
    {
      name: 'Star_burst',
      texture: 'star-02',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 2,
      looping: false,
      life: range(0.35, 0.9),
      speed: range(15, 22),
      size: range(0.75, 1.75),
      gravity: 0,
      rate: 0,
      burst: constant(3),
      shape: { kind: 'cone', angle: 0, radius: 0.75 },
      sizeCurve: starPop,
      rotateOverLife: true,
      color: limeToWhite,
      localEuler: unityUp,
    },
  ],
}

export const burgerShopUnlock: BurgerShopRecipe = {
  id: 'unlock-area',
  label: 'Unlock area',
  unityPrefab: 'FX_Unlock_Area_01',
  duration: 2,
  looping: false,
  emitters: [
    {
      name: 'Trail',
      texture: 'mask-01',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'additive',
      duration: 2,
      looping: false,
      life: range(0.3, 0.5),
      speed: range(12, 25),
      size: constant(0),
      gravity: 0,
      rate: 0,
      burst: constant(7),
      shape: { kind: 'cone', angle: 0, radius: 2 },
      trailLife: 0.5,
      color: confetti,
      localEuler: unityUp,
    },
    {
      name: 'Sparkles',
      texture: 'sparkle',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 0.5,
      looping: false,
      life: range(0.35, 0.9),
      speed: constant(0),
      size: range(1, 3),
      gravity: 0,
      rate: 12,
      burst: constant(3),
      shape: { kind: 'hemisphere', radius: 2 },
      sizeCurve: twinkle,
      color: limeToMint,
      localEuler: unityUp,
    },
    {
      name: 'Star_burst',
      texture: 'star-02',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 2,
      looping: false,
      life: range(0.35, 0.9),
      speed: range(15, 18),
      size: range(0.75, 1.75),
      gravity: 0,
      rate: 0,
      burst: constant(3),
      shape: { kind: 'cone', angle: 0, radius: 0.75 },
      sizeCurve: starPop,
      rotateOverLife: true,
      color: limeToWhite,
      localEuler: unityUp,
    },
    {
      name: 'Star_rate',
      texture: 'star-02',
      sheet: { columns: 1, rows: 1 },
      billboard: 'camera',
      blend: 'cutout',
      duration: 0.5,
      looping: false,
      life: range(0.35, 0.9),
      speed: range(8, 22),
      size: range(0.8, 1.8),
      gravity: 0,
      rate: 9,
      burst: constant(0),
      shape: { kind: 'cone', angle: 0, radius: 2 },
      sizeCurve: starPop,
      rotateOverLife: true,
      color: limeToWhite,
      localEuler: unityUp,
    },
    {
      name: 'Arrow',
      texture: 'arrow',
      sheet: { columns: 1, rows: 1 },
      billboard: 'vertical',
      blend: 'cutout',
      duration: 2,
      looping: false,
      life: constant(0.75),
      speed: constant(26),
      size: constant(4),
      gravity: 0,
      rate: 0,
      burst: constant(1),
      shape: { kind: 'point' },
      sizeCurve: popIn,
      color: limeToMint,
      localEuler: unityUp,
    },
  ],
}

export const BURGER_SHOP_RECIPES: BurgerShopRecipe[] = [
  burgerShopFootsteps,
  burgerShopCharacterUpgrade,
  burgerShopConfetti01,
  burgerShopConfetti02,
  burgerShopEating,
  burgerShopFlies,
  burgerShopPoof01,
  burgerShopPoof02,
  burgerShopSmoke,
  burgerShopSunshine,
  burgerShopTableFirstPurchase,
  burgerShopTableUpgrade,
  burgerShopUnlock,
]

export const BURGER_SHOP_RECIPE_IDS = BURGER_SHOP_RECIPES.map((recipe) => recipe.id)

export function nextBurgerShopRecipeId(id: string): string {
  const index = BURGER_SHOP_RECIPE_IDS.indexOf(id)
  return BURGER_SHOP_RECIPE_IDS[(index + 1) % BURGER_SHOP_RECIPE_IDS.length]
}

export function previousBurgerShopRecipeId(id: string): string {
  const index = BURGER_SHOP_RECIPE_IDS.indexOf(id)
  return BURGER_SHOP_RECIPE_IDS[(index - 1 + BURGER_SHOP_RECIPE_IDS.length) % BURGER_SHOP_RECIPE_IDS.length]
}
