// Public entry point. Re-exports the layered split modules.

export { exportPfxComponentSnippet, exportPfxPresetJson } from './build'
export { ART_STYLE_CLUSTERS, EFFECT_TYPE_FILTERS, PERFORMANCE_TIER_BUDGETS, PFX_BEHAVIOR_ROLE_REVIEW_ORDER, PFX_CONTROL_DEFINITIONS, PFX_MARKET_SOURCE_REFERENCES, PFX_MOBILE_RUNTIME_POLICY, PFX_PRODUCTION_IMPLEMENTATION_CANDIDATE_PREREQUISITES, PFX_PRODUCTION_IMPLEMENTATION_CRITERIA, PFX_QUALITY_RUBRIC_KEYS, PFX_RED_TEAM_CRITERIA, PFX_TAXONOMY_REVIEW_CRITERIA, PFX_TEXTURE_ATLAS, PFX_TEXTURE_KINDS, createPfxComboRingVariantRecipe, getPfxStyleRenderProfile, getPfxStyleRenderSignature, getPfxTextureAtlasSlice } from './constants/01'
export { AUTHORED_EFFECT_RECIPES } from './constants/02'
export { PFX_CC0_ASSET_SOURCES, PFX_CERTIFIED_EFFECTS, getPfxGroupWorkList } from './constants/03'
export { PFX_PARTICLE_BASE_SIZE, clearPfxRuntimeResourceCache, createPfxFlameBurstGeometry, createPfxFlameBurstLifecycle, createPfxFlameBurstRuntimeState, createPfxMeteorBurstGeometry, getPfxMuzzleFlashAtlasTexture, getPfxParticleMotionKind, getPfxParticleShapeProfile, getPfxRuntimeResourceCacheStats, getPfxSharedFireballFlipbookTexture, getPfxSharedFlameFlipbookTexture, getPfxSharedGeometry, getPfxSharedParticleTexture, getPfxSharedSpriteAtlasTexture, validatePfxPreset } from './constants/04'
export { createPfxComboRingMaterial, createPfxExhaustTelegraphMaterial, createPfxHologramBreakMaterial, createPfxMarkerReleaseMaterial, createPfxScanConeMaterial, createPfxTargetSpawnMaterial, createPfxThrusterTrailMaterial, createPfxUiPickupMaterial, createPfxWarningLoopMaterial, getPfxPlasmaImpactFlipbookTexture, getPfxSharedGradientTexture } from './constants/05'
export { PFX_PROJECTILE_WAKE_HEAD_COLLAR_OPACITY, createPfxExhaustTelegraphLifecycle, createPfxFlameBurstMaterial, createPfxHologramBreakLifecycle, createPfxHologramBreakRuntimeState, createPfxMarkerReleaseLifecycle, createPfxMarkerReleaseRuntimeState, createPfxMeshShaderHotColor, createPfxMeshShaderRenderPolicy, createPfxMeteorBurstMaterial, createPfxScanConeLifecycle, createPfxScanConeRuntimeState, createPfxThrusterTrailLifecycle, createPfxThrusterTrailRuntimeState, createPfxWarningLoopLifecycle, createPfxWarningLoopRuntimeState } from './constants/06'
export { PFX_MOBILE_DEVICE_BENCHMARKS, PFX_PROJECTILE_COMET_TAIL_LOBES, PFX_SMOKE_BILLOW_LOBES, PFX_SPAWN_VOXEL_LAYOUT, createPfxComboRingLifecycle, createPfxComboRingRuntimeState, createPfxEmitterPhysicsFindings, createPfxExhaustTelegraphRuntimeState, createPfxMeteorBurstLifecycle, createPfxMeteorBurstRuntimeState, createPfxTargetSpawnLifecycle, createPfxTargetSpawnRuntimeState, createPfxUiPickupLifecycle, createPfxUiPickupRuntimeState, getPfxParticleLifeAlpha, isPfxSurfaceCameraFacing, shouldApplyPfxSurfaceCameraFacing, shouldRotatePfxBurstPattern, updatePfxParticleSimulation } from './constants/07'
export { createPfxAcidBurstLifecycle } from './effects/acidBurst'
export { createPfxAcidBurstCrownGeometry, createPfxAcidBurstCrownMaterial } from './effects/acidBurstCrown'
export { createPfxAcidBurstDropletGeometry, createPfxAcidBurstDropletMaterial } from './effects/acidBurstDroplet'
export { applyPfxAcidBurstMaterialAppearance } from './effects/acidBurstMaterial'
export { createPfxAcidIdleLifecycle } from './effects/acidIdle'
export { createPfxAcidPoolGeometry } from './effects/acidPool'
export { createPfxAcidSpawnGeometry, createPfxAcidSpawnLifecycle, createPfxAcidSpawnMaterial } from './effects/acidSpawn'
export { applyPfxAcidSpawnMaterialAppearance } from './effects/acidSpawnMaterial'
export { createPfxArcSweepWindow } from './effects/arcSweep'
export { createPfxArcSweepErosionStrength } from './effects/arcSweepErosionStrength'
export { createPfxBarrierBreachRibGeometry, createPfxBarrierBreachRibMaterial } from './effects/barrierBreachRib'
export { createPfxBarrierColumnGeometry, createPfxBarrierColumnMaterial } from './effects/barrierColumn'
export { applyPfxBarrierColumnMaterialAppearance } from './effects/barrierColumnMaterial'
export { createPfxBarrierLowHealthGeometry, createPfxBarrierLowHealthMaterial } from './effects/barrierLowHealth'
export { createPfxBeamTelegraphMaterial } from './effects/beamTelegraph'
export { createPfxBeamTelegraphApertureGeometry } from './effects/beamTelegraphAperture'
export { createPfxBeamTelegraphLaneGeometry } from './effects/beamTelegraphLane'
export { applyPfxBeamTelegraphMaterialAppearance } from './effects/beamTelegraphMaterial'
export { createPfxBlastBeamGeometry, createPfxBlastBeamLifecycle } from './effects/blastBeam'
export { createPfxBlastBurstGeometry, createPfxBlastBurstLifecycle, createPfxBlastBurstMaterial, createPfxBlastBurstRuntimeState } from './effects/blastBurst'
export { createPfxBlastBurstStyleTreatment } from './effects/blastBurstStyle'
export { createPfxBloodDeathGeometry, createPfxBloodDeathLifecycle, createPfxBloodDeathMaterial } from './effects/bloodDeath'
export { applyPfxBloodDeathMaterialAppearance } from './effects/bloodDeathMaterial'
export { createPfxCoinRewardBurstGeometry, createPfxCoinRewardBurstMaterial } from './effects/coinRewardBurst'
export { applyPfxComboRingMaterialAppearance } from './effects/comboRingMaterial'
export { createPfxCurseBurstLifecycle } from './effects/curseBurst'
export { createPfxCurseBurstBindingGeometry, createPfxCurseBurstBindingMaterial } from './effects/curseBurstBinding'
export { createPfxCurseBurstEffigyGeometry, createPfxCurseBurstEffigyMaterial } from './effects/curseBurstEffigy'
export { applyPfxCurseBurstMaterialAppearance } from './effects/curseBurstMaterial'
export { createPfxCurseColumnGeometry, createPfxCurseColumnLifecycle } from './effects/curseColumn'
export { createPfxCurseConeGeometry, createPfxCurseConeLifecycle, createPfxCurseConeMaterial } from './effects/curseCone'
export { applyPfxCurseConeMaterialAppearance } from './effects/curseConeMaterial'
export { getPfxCycleScale } from './effects/cycleScale'
export { createPfxDashIdleGeometry, createPfxDashIdleMaterial } from './effects/dashIdle'
export { applyPfxDashIdleMaterialAppearance } from './effects/dashIdleMaterial'
export { createPfxDebrisBurstGeometry, createPfxDebrisBurstLifecycle, createPfxDebrisBurstMaterial, createPfxDebrisBurstRuntimeState } from './effects/debrisBurst'
export { createPfxDebrisBurstStyleTreatment } from './effects/debrisBurstStyle'
export { createPfxDebrisMissFragmentGeometry, createPfxDebrisMissFragmentMaterial } from './effects/debrisMissFragment'
export { createPfxDebrisReleaseFragmentGeometry, createPfxDebrisReleaseFragmentMaterial } from './effects/debrisReleaseFragment'
export { createPfxDespawnImpactGeometry, createPfxDespawnImpactLifecycle, createPfxDespawnImpactMaterial } from './effects/despawnImpact'
export { applyPfxDespawnImpactMaterialAppearance } from './effects/despawnImpactMaterial'
export { createPfxDustBurstGeometry, createPfxDustBurstLifecycle, createPfxDustBurstMaterial, createPfxDustBurstRuntimeState } from './effects/dustBurst'
export { createPfxDustBurstStyleTreatment } from './effects/dustBurstStyle'
export { applyPfxElectricCriticalAppearance, createPfxElectricCriticalMaterial } from './effects/electricCritical'
export { createPfxElectricCriticalDiagonalDischargeGeometry } from './effects/electricCriticalDiagonalDischarge'
export { createPfxElectricCriticalImpactStarburstGeometry } from './effects/electricCriticalImpactStarburst'
export { createPfxElectricCriticalNexusGeometry, createPfxElectricCriticalNexusMaterial } from './effects/electricCriticalNexus'
export { createPfxElectricCriticalVoltageCageGeometry } from './effects/electricCriticalVoltageCage'
export { createPfxElectricTrailLifecycle } from './effects/electricTrail'
export { createPfxElectricWakeGeometry } from './effects/electricWake'
export { createPfxEmberFragmentGeometry, createPfxEmberFragmentMaterial } from './effects/emberFragment'
export { createPfxEmberIgnitionGeometry, createPfxEmberIgnitionMaterial } from './effects/emberIgnition'
export { createPfxExhaustHitNozzleGeometry, createPfxExhaustHitNozzleMaterial } from './effects/exhaustHitNozzle'
export { createPfxExhaustTelegraphStyleTreatment } from './effects/exhaustTelegraphStyle'
export { createPfxFlameBurstStyleTreatment } from './effects/flameBurstStyle'
export { createPfxFlameChargeCrucibleGeometry, createPfxFlameChargeCrucibleMaterial } from './effects/flameChargeCrucible'
export { getPfxFlameChargeLightProfile } from './effects/flameChargeLightProfile'
export { createPfxFlameChargeTendrilGeometry, createPfxFlameChargeTendrilMaterial } from './effects/flameChargeTendril'
export { getPfxFlipbookFrameProps } from './effects/flipbookFrameProps'
export { createPfxFootstepAmbientGeometry, createPfxFootstepAmbientMaterial } from './effects/footstepAmbient'
export { applyPfxFootstepAmbientMaterialAppearance } from './effects/footstepAmbientMaterial'
export { createPfxFrostAuraGeometry, createPfxFrostAuraMaterial } from './effects/frostAura'
export { createPfxFrostAuraCrystalGlintMaterial } from './effects/frostAuraCrystalGlint'
export { applyPfxFrostAuraMaterialCycle, applyPfxFrostAuraMaterialOpacity } from './effects/frostAuraMaterial'
export { createPfxGhostCriticalTalonGeometry, createPfxGhostCriticalTalonMaterial } from './effects/ghostCriticalTalon'
export { createPfxGhostTrailGeometry, createPfxGhostTrailLifecycle, createPfxGhostTrailMaterial } from './effects/ghostTrail'
export { applyPfxGhostTrailMaterialAppearance } from './effects/ghostTrailMaterial'
export { createPfxGlyphRingLifecycle } from './effects/glyphRing'
export { createPfxGlyphTrailLifecycle, createPfxGlyphTrailMaterial, createPfxGlyphTrailRuntimeState } from './effects/glyphTrail'
export { createPfxGlyphTrailLeadSigilGeometry } from './effects/glyphTrailLeadSigil'
export { applyPfxGlyphTrailMaterialCycle, applyPfxGlyphTrailMaterialOpacity } from './effects/glyphTrailMaterial'
export { createPfxGlyphTrailRuneChainGeometry } from './effects/glyphTrailRuneChain'
export { createPfxGlyphTrailStyleTreatment } from './effects/glyphTrailStyle'
export { createPfxHealingBurstLifecycle } from './effects/healingBurst'
export { createPfxHealingBurstBloomGeometry, createPfxHealingBurstBloomMaterial } from './effects/healingBurstBloom'
export { createPfxHealingBurstLeafGeometry, createPfxHealingBurstLeafMaterial } from './effects/healingBurstLeaf'
export { applyPfxHealingBurstMaterialAppearance } from './effects/healingBurstMaterial'
export { createPfxHealingBurstReferenceGeometry, createPfxHealingBurstReferenceMaterial } from './effects/healingBurstReference'
export { createPfxHealingFocalGeometry, createPfxHealingFocalMaterial } from './effects/healingFocal'
export { createPfxHealingGlyphGeometry, createPfxHealingGlyphLayout, createPfxHealingGlyphMaterial } from './effects/healingGlyph'
export { createPfxHealingLeafProgress } from './effects/healingLeaf'
export { createPfxHealingLeafEdgeMaterial } from './effects/healingLeafEdge'
export { createPfxHealingLeafHelixLayout } from './effects/healingLeafHelix'
export { createPfxHealingLoopGeometry, createPfxHealingLoopLifecycle, createPfxHealingLoopMaterial } from './effects/healingLoop'
export { applyPfxHealingLoopMaterialAppearance } from './effects/healingLoopMaterial'
export { createPfxHealingRestorationPulse } from './effects/healingRestorationPulse'
export { createPfxHealingSparkleGeometry, createPfxHealingSparkleLayout } from './effects/healingSparkle'
export { createPfxHealingVineGeometry, createPfxHealingVineMaterial } from './effects/healingVine'
export { createPfxHealingVinePoint } from './effects/healingVinePoint'
export { createPfxHeldProjectileLifecycle } from './effects/heldProjectile'
export { createPfxHologramAuraLifecycle } from './effects/hologramAura'
export { createPfxHolyBurstLifecycle } from './effects/holyBurst'
export { createPfxHolyBurstFeatherGeometry, createPfxHolyBurstFeatherMaterial } from './effects/holyBurstFeather'
export { applyPfxHolyBurstMaterialAppearance } from './effects/holyBurstMaterial'
export { createPfxHolyBurstReferenceGeometry, createPfxHolyBurstReferenceMaterial } from './effects/holyBurstReference'
export { createPfxHolyBurstSunGeometry, createPfxHolyBurstSunMaterial } from './effects/holyBurstSun'
export { createPfxHolyReleaseGeometry, createPfxHolyReleaseLifecycle, createPfxHolyReleaseMaterial } from './effects/holyRelease'
export { applyPfxHolyReleaseMaterialAppearance } from './effects/holyReleaseMaterial'
export { applyPfxIceImpactAppearance, createPfxIceImpactGeometry, createPfxIceImpactMaterial } from './effects/iceImpact'
export { createPfxIceImpactChipGeometry } from './effects/iceImpactChip'
export { applyPfxIceImpactMaterialOpacity } from './effects/iceImpactMaterial'
export { createPfxImpactCoreGeometry, createPfxImpactCoreMaterial } from './effects/impactCore'
export { createPfxImpactShardBurstGeometry, createPfxImpactShardBurstMaterial } from './effects/impactShardBurst'
export { createPfxJumpBeamGeometry, createPfxJumpBeamMaterial } from './effects/jumpBeam'
export { applyPfxJumpBeamMaterialAppearance } from './effects/jumpBeamMaterial'
export { createPfxJumpPickupLifecycle } from './effects/jumpPickup'
export { createPfxJumpPickupCradleGeometry, createPfxJumpPickupCradleMaterial } from './effects/jumpPickupCradle'
export { createPfxJumpPickupRewardGemGeometry, createPfxJumpPickupRewardGemMaterial } from './effects/jumpPickupRewardGem'
export { createPfxLaserSprayMaterial } from './effects/laserSpray'
export { createPfxLaserSprayBoltRackGeometry } from './effects/laserSprayBoltRack'
export { applyPfxLaserSprayMaterialAppearance } from './effects/laserSprayMaterial'
export { createPfxLaserSprayNozzleGeometry } from './effects/laserSprayNozzle'
export { getPfxLaserSprayShotVisibility } from './effects/laserSprayShotVisibility'
export { createPfxLeafBurstLifecycle } from './effects/leafBurst'
export { createPfxLeafBurstCanopyGeometry, createPfxLeafBurstCanopyMaterial } from './effects/leafBurstCanopy'
export { applyPfxLeafBurstMaterialAppearance } from './effects/leafBurstMaterial'
export { createPfxLeafBurstVeinGeometry, createPfxLeafBurstVeinMaterial } from './effects/leafBurstVein'
export { createPfxLevelUpSurgeLifecycle } from './effects/levelUpSurge'
export { createPfxMagicCircleGeometry, createPfxMagicCircleMaterial } from './effects/magicCircle'
export { getPfxMeshBreakProgress } from './effects/meshBreak'
export { createPfxMeteorBurstStyleTreatment } from './effects/meteorBurstStyle'
export { createPfxMeteorChunkGeometry, createPfxMeteorChunkLayout, createPfxMeteorChunkMaterial } from './effects/meteorChunk'
export { createPfxMeteorHeatFrontGeometry } from './effects/meteorHeatFront'
export { applyPfxMeteorImpactAppearance, createPfxMeteorImpactGeometry, createPfxMeteorImpactMaterial } from './effects/meteorImpact'
export { getPfxMeteorImpactLightProfile } from './effects/meteorImpactLightProfile'
export { createPfxMobileRuntimePolicy } from './effects/mobileRuntimePolicy'
export { createPfxMudBurstLifecycle } from './effects/mudBurst'
export { createPfxMudBurstClodGeometry, createPfxMudBurstClodMaterial } from './effects/mudBurstClod'
export { createPfxMudBurstCrownGeometry, createPfxMudBurstCrownMaterial } from './effects/mudBurstCrown'
export { applyPfxMudBurstMaterialAppearance } from './effects/mudBurstMaterial'
export { createPfxMudBurstRainReferenceGeometry } from './effects/mudBurstRainReference'
export { createPfxMudBurstReferenceGeometry, createPfxMudBurstReferenceMaterial } from './effects/mudBurstReference'
export { createPfxMudChargeGeometry, createPfxMudChargeLifecycle, createPfxMudChargeMaterial } from './effects/mudCharge'
export { applyPfxMudChargeMaterialAppearance } from './effects/mudChargeMaterial'
export { createPfxMuzzleFlameGeometry, createPfxMuzzleFlameMaterial } from './effects/muzzleFlame'
export { getPfxParticleColorRamp } from './effects/particleColor'
export { createPfxParticleSimulation } from './effects/particleSimulation'
export { createPfxPetalAmbientGeometry, createPfxPetalAmbientLifecycle, createPfxPetalAmbientMaterial } from './effects/petalAmbient'
export { applyPfxPetalAmbientMaterialAppearance } from './effects/petalAmbientMaterial'
export { createPfxPetalBurstLifecycle } from './effects/petalBurst'
export { createPfxPetalBurstCanopyGeometry, createPfxPetalBurstCanopyMaterial } from './effects/petalBurstCanopy'
export { applyPfxPetalBurstMaterialAppearance } from './effects/petalBurstMaterial'
export { createPfxPetalBurstStamenGeometry, createPfxPetalBurstStamenMaterial } from './effects/petalBurstStamen'
export { createPfxPickupBurstGeometry, createPfxPickupBurstMaterial } from './effects/pickupBurst'
export { applyPfxPickupBurstMaterialAppearance } from './effects/pickupBurstMaterial'
export { createPfxPlasmaAmbientCoreGeometry, createPfxPlasmaAmbientCoreMaterial } from './effects/plasmaAmbientCore'
export { createPfxPlasmaAmbientOrbitGeometry, createPfxPlasmaAmbientOrbitMaterial } from './effects/plasmaAmbientOrbit'
export { createPfxPlasmaHitMaterial } from './effects/plasmaHit'
export { createPfxPlasmaHitContactGeometry } from './effects/plasmaHitContact'
export { createPfxPlasmaHitFluxGeometry } from './effects/plasmaHitFlux'
export { applyPfxPlasmaHitMaterialAppearance } from './effects/plasmaHitMaterial'
export { applyPfxPlasmaImpactFlipbookAppearance, createPfxPlasmaImpactFlipbookMaterial } from './effects/plasmaImpactFlipbook'
export { createPfxPlasmaImpactVolumeGeometry } from './effects/plasmaImpactVolume'
export { createPfxPoisonBurstLifecycle } from './effects/poisonBurst'
export { createPfxPoisonBurstBloomGeometry, createPfxPoisonBurstBloomMaterial } from './effects/poisonBurstBloom'
export { applyPfxPoisonBurstMaterialAppearance } from './effects/poisonBurstMaterial'
export { createPfxPoisonBurstSporeGeometry, createPfxPoisonBurstSporeMaterial } from './effects/poisonBurstSpore'
export { createPfxPortalChargeLifecycle } from './effects/portalCharge'
export { createPfxPortalTelegraphGeometry, createPfxPortalTelegraphLifecycle, createPfxPortalTelegraphMaterial } from './effects/portalTelegraph'
export { applyPfxPortalTelegraphMaterialAppearance } from './effects/portalTelegraphMaterial'
export { createPfxPortalThroatGeometry } from './effects/portalThroat'
export { createPfxProjectileWakeGeometry } from './effects/projectileWake'
export { createPfxProjectileWakeEnvelope } from './effects/projectileWakeEnvelope'
export { createPfxRainBurstGeometry, createPfxRainBurstLifecycle, createPfxRainBurstMaterial } from './effects/rainBurst'
export { createPfxRainBurstFoamGeometry, createPfxRainBurstFoamMaterial } from './effects/rainBurstFoam'
export { applyPfxRainBurstMaterialAppearance } from './effects/rainBurstMaterial'
export { createPfxRewardChargeGeometry, createPfxRewardChargeMaterial } from './effects/rewardCharge'
export { applyPfxRewardChargeMaterialAppearance } from './effects/rewardChargeMaterial'
export { getPfxRewardGemFacetColors } from './effects/rewardGemFacetColors'
export { createPfxRewardTelegraphLifecycle } from './effects/rewardTelegraph'
export { getPfxRingPlaneRotation } from './effects/ringPlaneRotation'
export { createPfxSandBurstGeometry, createPfxSandBurstLifecycle, createPfxSandBurstMaterial } from './effects/sandBurst'
export { applyPfxSandBurstMaterialAppearance } from './effects/sandBurstMaterial'
export { createPfxSandSprayLifecycle } from './effects/sandSpray'
export { createPfxShadowBreakGeometry, createPfxShadowBreakLifecycle, createPfxShadowBreakMaterial } from './effects/shadowBreak'
export { applyPfxShadowBreakMaterialAppearance } from './effects/shadowBreakMaterial'
export { createPfxShadowBurstLifecycle } from './effects/shadowBurst'
export { createPfxShadowBurstBloomGeometry, createPfxShadowBurstBloomMaterial } from './effects/shadowBurstBloom'
export { createPfxShadowBurstClawGeometry, createPfxShadowBurstClawMaterial } from './effects/shadowBurstClaw'
export { createPfxShadowBurstFragmentGeometry, createPfxShadowBurstFragmentMaterial } from './effects/shadowBurstFragment'
export { createPfxShadowBurstLegGeometry, createPfxShadowBurstLegMaterial } from './effects/shadowBurstLeg'
export { applyPfxShadowBurstMaterialAppearance } from './effects/shadowBurstMaterial'
export { createPfxShadowBurstReferenceGeometry, createPfxShadowBurstReferenceMaterial } from './effects/shadowBurstReference'
export { createPfxShadowBurstSpiderGeometry, createPfxShadowBurstSpiderMaterial } from './effects/shadowBurstSpider'
export { createPfxShadowBurstSplinterGeometry, createPfxShadowBurstSplinterMaterial } from './effects/shadowBurstSplinter'
export { createPfxShardBreakFragmentGeometry, createPfxShardBreakFragmentMaterial } from './effects/shardBreakFragment'
export { createPfxShardBreakIgnitionCoreGeometry } from './effects/shardBreakIgnitionCore'
export { applyPfxShardBreakMaterialOpacity } from './effects/shardBreakMaterial'
export { createPfxShieldFragmentGeometry, createPfxShieldFragmentMaterial } from './effects/shieldFragment'
export { createPfxShockwaveBurstGeometry, createPfxShockwaveBurstLifecycle, createPfxShockwaveBurstMaterial, createPfxShockwaveBurstRuntimeState } from './effects/shockwaveBurst'
export { createPfxShockwaveBurstStyleTreatment } from './effects/shockwaveBurstStyle'
export { createPfxShockwaveSpawnArrivalFlareGeometry, createPfxShockwaveSpawnArrivalFlareMaterial } from './effects/shockwaveSpawnArrivalFlare'
export { createPfxShockwaveSpawnPressureFrontGeometry, createPfxShockwaveSpawnPressureFrontMaterial } from './effects/shockwaveSpawnPressureFront'
export { createPfxSlashArcGeometry } from './effects/slashArc'
export { createPfxSlimeBurstLifecycle } from './effects/slimeBurst'
export { createPfxSlimeBurstBubbleGeometry, createPfxSlimeBurstBubbleMaterial } from './effects/slimeBurstBubble'
export { createPfxSlimeBurstCrownGeometry, createPfxSlimeBurstCrownMaterial } from './effects/slimeBurstCrown'
export { applyPfxSlimeBurstMaterialAppearance } from './effects/slimeBurstMaterial'
export { createPfxSlimeRingGeometry, createPfxSlimeRingLifecycle, createPfxSlimeRingMaterial } from './effects/slimeRing'
export { applyPfxSlimeRingMaterialAppearance } from './effects/slimeRingMaterial'
export { createPfxSnowBurstLifecycle } from './effects/snowBurst'
export { createPfxSnowBurstCrystalGeometry, createPfxSnowBurstCrystalMaterial } from './effects/snowBurstCrystal'
export { applyPfxSnowBurstMaterialAppearance } from './effects/snowBurstMaterial'
export { createPfxSnowBurstPowderGeometry, createPfxSnowBurstPowderMaterial } from './effects/snowBurstPowder'
export { createPfxSnowIdleLifecycle } from './effects/snowIdle'
export { createPfxSnowIdleFlurryGeometry, createPfxSnowIdleFlurryMaterial } from './effects/snowIdleFlurry'
export { createPfxSnowIdleGranuleGeometry, createPfxSnowIdleGranuleMaterial } from './effects/snowIdleGranule'
export { applyPfxSnowIdleMaterialAppearance } from './effects/snowIdleMaterial'
export { createPfxSnowSpawnCradleGeometry, createPfxSnowSpawnCradleMaterial } from './effects/snowSpawnCradle'
export { applyPfxSparkConeMaterialOpacity } from './effects/sparkConeMaterial'
export { createPfxSparkConeStreakGeometry, createPfxSparkConeStreakMaterial } from './effects/sparkConeStreak'
export { createPfxSpawnScreenLifecycle } from './effects/spawnScreen'
export { createPfxSpawnScreenReticleGeometry, createPfxSpawnScreenReticleMaterial } from './effects/spawnScreenReticle'
export { createPfxSpriteEmissionMaterial } from './effects/spriteEmission'
export { getPfxSpriteForSurface } from './effects/spriteForSurface'
export { getPfxSpriteVariantLayout } from './effects/spriteVariant'
export { getPfxSurfaceColorIndex } from './effects/surfaceColorIndex'
export { getPfxSurfaceMaterialProps } from './effects/surfaceMaterialProps'
export { getPfxSurfacePositionOffset } from './effects/surfacePositionOffset'
export { applyPfxSurfaceRotation } from './effects/surfaceRotation'
export { getPfxSurfaceSpatialPolicy } from './effects/surfaceSpatialPolicy'
export { createPfxTargetBreakFragmentGeometry, createPfxTargetBreakFragmentMaterial } from './effects/targetBreakFragment'
export { createPfxTargetBreakReticleGeometry, createPfxTargetBreakReticleMaterial } from './effects/targetBreakReticle'
export { createPfxTargetLockShellGeometry } from './effects/targetLockShell'
export { createPfxTeleportHitGeometry, createPfxTeleportHitLifecycle, createPfxTeleportHitMaterial } from './effects/teleportHit'
export { applyPfxTeleportHitMaterialAppearance } from './effects/teleportHitMaterial'
export { createPfxWarpSprayFacetGeometry, createPfxWarpSprayFacetMaterial } from './effects/warpSprayFacet'
export { createPfxWaterColumnGeometry, createPfxWaterColumnLifecycle, createPfxWaterColumnMaterial } from './effects/waterColumn'
export { createPfxWaterColumnFoamGeometry, createPfxWaterColumnFoamMaterial } from './effects/waterColumnFoam'
export { applyPfxWaterColumnMaterialAppearance } from './effects/waterColumnMaterial'
export { createPfxWaterConeGeometry, createPfxWaterConeLifecycle } from './effects/waterCone'
export { createPfxWindBeamLifecycle } from './effects/windBeam'
export { createPfxWindBeamLeafGeometry, createPfxWindBeamLeafMaterial } from './effects/windBeamLeaf'
export { applyPfxWindBeamLeafMaterialAppearance } from './effects/windBeamLeafMaterial'
export { createPfxWindBeamPressureGeometry, createPfxWindBeamPressureMaterial } from './effects/windBeamPressure'
export { applyPfxWindBeamPressureMaterialAppearance } from './effects/windBeamPressureMaterial'
export { createPfxWindBurstLifecycle } from './effects/windBurst'
export { applyPfxWindBurstMaterialAppearance } from './effects/windBurstMaterial'
export { createPfxWindBurstPressureGeometry, createPfxWindBurstPressureMaterial } from './effects/windBurstPressure'
export { createPfxWindBurstWakeGeometry, createPfxWindBurstWakeMaterial } from './effects/windBurstWake'
export { createPfxWindImpactLifecycle } from './effects/windImpact'
export { createPfxWindPressureGeometry, createPfxWindPressureMaterial } from './effects/windPressure'
export { PFX_COMPONENT_DEFINITIONS, PFX_PRESETS, PFX_TAXONOMY, createPfxClipAsset, createPfxControlExtremesContactSheetAsset, createPfxControlSafetyMatrix, createPfxDeveloperDocsManifest, createPfxExportCleanlinessAudit, createPfxParticleEmission, createPfxPreset, createPfxPreviewAssetAudit, createPfxPreviewManifest, createPfxRuntimeOptimizationAudit, createPfxSimParticleCount, createPfxStressScenario, createPfxStructuralQualityAudit, createPfxStyleContactSheetAsset, createPfxStyleDifferentiationMatrix, createPfxThumbnailAsset, createReducedMotionPfxPreset, exportPfxDeveloperDocsManifestJson, exportPfxDeveloperDocsMarkdown, exportPfxPreviewManifestJson, filterPfxCatalog, getPfxComponentDefinition, getPfxRenderPlan, summarizePfxPerformance } from './tooling/01'
export { createPfxExternalEvidenceBatchPlan, createPfxExternalEvidenceBatchSheet, createPfxExternalEvidenceBatchSheetIndex, createPfxExternalEvidenceWorkOrder, createPfxObjectiveReadinessReport, createPfxProductionReadinessReport, exportPfxExternalEvidenceBatchPlanMarkdown, exportPfxExternalEvidenceBatchSheetIndexMarkdown, exportPfxExternalEvidenceBatchSheetMarkdown, exportPfxExternalEvidenceWorkOrderMarkdown, exportPfxObjectiveReadinessReportMarkdown, exportPfxProductionReadinessReportJson } from './tooling/02'
export { createPfxProductionAcceptanceGapAudit, createPfxProductionApprovalBatchSheet, createPfxProductionApprovalBatchSheetIndex, createPfxProductionApprovalReadinessReport, createPfxProductionApprovalTemplate, createPfxProductionImplementationDossier, createPfxProductionImplementationTemplate, createPfxTaxonomyReviewBatchSheet, createPfxTaxonomyReviewBatchSheetIndex, createPfxTaxonomyReviewDossier, createPfxTaxonomyReviewManifestFromSources, createPfxTaxonomyReviewTemplate, exportPfxProductionAcceptanceGapAuditJson, exportPfxProductionAcceptanceGapAuditMarkdown, exportPfxProductionApprovalBatchSheetIndexMarkdown, exportPfxProductionApprovalBatchSheetMarkdown, exportPfxProductionApprovalReadinessReportJson, exportPfxProductionApprovalReadinessReportMarkdown, exportPfxProductionApprovalTemplateJson, exportPfxProductionImplementationDossierJson, exportPfxProductionImplementationTemplateJson, exportPfxTaxonomyReviewBatchSheetIndexMarkdown, exportPfxTaxonomyReviewBatchSheetMarkdown, exportPfxTaxonomyReviewDossierJson, exportPfxTaxonomyReviewDossierMarkdown, exportPfxTaxonomyReviewTemplateJson, validatePfxExternalEvidenceBatchSheetIndex } from './tooling/03'
export { createPfxProductionImplementationBatchSheet, createPfxProductionImplementationBatchSheetIndex, createPfxProductionImplementationCandidateReport, createPfxProductionImplementationManifestFromCandidates, createPfxRedTeamBlockingReviewManifest, createPfxRedTeamReviewBatchSheet, createPfxRedTeamReviewBatchSheetIndex, createPfxRedTeamReviewDossier, createPfxRedTeamReviewTemplate, createPfxSparkGapLoopState, exportPfxProductionImplementationBatchSheetIndexMarkdown, exportPfxProductionImplementationBatchSheetMarkdown, exportPfxProductionImplementationCandidateReportJson, exportPfxProductionImplementationDossierMarkdown, exportPfxRedTeamReviewBatchSheetIndexMarkdown, exportPfxRedTeamReviewBatchSheetMarkdown, exportPfxRedTeamReviewDossierJson, exportPfxRedTeamReviewDossierMarkdown, exportPfxRedTeamReviewTemplateJson } from './tooling/04'
export { createPfxSparkGapGeometry, createPfxSparkGapMaterial, getPfxBurstCycleSeconds, getPfxSurfaceAnimationProps } from './tooling/05'
export { GamePfx, PFX_COMPONENTS, createGamePfxComponent, createPfxChoreographyAudit, createPfxEstimatedFrameCostMs, createPfxGroupReadinessReport, createPfxMobileBenchmarkReport, createPfxPeakLiveParticles, getPfxComputedMobileSafety } from './tooling/07'
export type { ArtStyleCluster, BlendMode, EffectSpace, EffectType, ExportSnippetOptions, LodLevel, LoopMode, MobileSafety, PerformanceTier, PfxAcceptanceStatus, PfxBehaviorRole, PfxCatalogItem, PfxClipAsset, PfxComponentDefinition, PfxContactSheetAsset, PfxControlDefinition, PfxControlKey, PfxControlSafetyControlEvidence, PfxControlSafetyEffectEvidence, PfxControlSafetyMatrix, PfxControls, PfxDeveloperDocsEffect, PfxDeveloperDocsManifest, PfxExportCleanlinessAudit, PfxExportCleanlinessAuditEffect, PfxExternalEvidenceBatch, PfxExternalEvidenceBatchPlan, PfxExternalEvidenceBatchPlanOptions, PfxExternalEvidenceBatchSheet, PfxExternalEvidenceBatchSheetEffect, PfxExternalEvidenceBatchSheetIndex, PfxExternalEvidenceBatchSheetIndexOptions, PfxExternalEvidenceBatchSheetIndexSheet, PfxExternalEvidenceBatchSheetIndexValidation, PfxExternalEvidenceBatchSheetOptions, PfxExternalEvidenceNextReadyWorkItem, PfxExternalEvidenceWorkItem, PfxExternalEvidenceWorkItemCounts, PfxExternalEvidenceWorkItemId, PfxExternalEvidenceWorkOrder, PfxExternalEvidenceWorkOrderEffect, PfxExternalEvidenceWorkOrderOptions, PfxFilterQuery, PfxMarketSourceFamily, PfxMobileRuntimePolicy, PfxObjectiveReadinessReport, PfxObjectiveReadinessRequirement, PfxObjectiveReadinessRequirementStatus, PfxPerformanceBudget, PfxPerformanceMetadata, PfxPerformanceSummary, PfxPreset, PfxPresetOverrides, PfxPreviewAssetAudit, PfxPreviewAssetAuditEffect, PfxPreviewDescriptor, PfxPreviewManifest, PfxPreviewManifestEntry, PfxProductionAcceptanceGap, PfxProductionAcceptanceGapAudit, PfxProductionAcceptanceGapEffect, PfxProductionAcceptanceGapKind, PfxProductionApproval, PfxProductionApprovalBatch, PfxProductionApprovalBatchSheet, PfxProductionApprovalBatchSheetEffect, PfxProductionApprovalBatchSheetIndex, PfxProductionApprovalBatchSheetIndexOptions, PfxProductionApprovalBatchSheetIndexSheet, PfxProductionApprovalBatchSheetOptions, PfxProductionApprovalCaptureHandoff, PfxProductionApprovalCaptureHandoffPlatform, PfxProductionApprovalDecision, PfxProductionApprovalReadinessEffect, PfxProductionApprovalReadinessMissingPrerequisite, PfxProductionApprovalReadinessReport, PfxProductionApprovalReadinessStatus, PfxProductionApprovalTemplate, PfxProductionApprovalTemplateOptions, PfxProductionImplementationBatch, PfxProductionImplementationBatchSheet, PfxProductionImplementationBatchSheetEffect, PfxProductionImplementationBatchSheetIndex, PfxProductionImplementationBatchSheetIndexOptions, PfxProductionImplementationBatchSheetIndexSheet, PfxProductionImplementationBatchSheetOptions, PfxProductionImplementationCandidateEffect, PfxProductionImplementationCandidatePrerequisite, PfxProductionImplementationCandidateReport, PfxProductionImplementationCandidateStatus, PfxProductionImplementationCriterion, PfxProductionImplementationCriterionStatus, PfxProductionImplementationDossier, PfxProductionImplementationDossierEffect, PfxProductionImplementationManifestFromCandidatesOptions, PfxProductionImplementationReview, PfxProductionImplementationStatus, PfxProductionImplementationTemplate, PfxProductionReadinessEffect, PfxProductionReadinessOptions, PfxProductionReadinessReport, PfxProductionReadinessStatus, PfxQualityRubricKey, PfxQualityScore, PfxQualityScores, PfxRedTeamBlockingReviewManifestOptions, PfxRedTeamCriterion, PfxRedTeamCriterionStatus, PfxRedTeamEffectReview, PfxRedTeamReviewBatch, PfxRedTeamReviewBatchSheet, PfxRedTeamReviewBatchSheetEffect, PfxRedTeamReviewBatchSheetIndex, PfxRedTeamReviewBatchSheetIndexOptions, PfxRedTeamReviewBatchSheetIndexSheet, PfxRedTeamReviewBatchSheetOptions, PfxRedTeamReviewDossier, PfxRedTeamReviewDossierEffect, PfxRedTeamReviewDossierOptions, PfxRedTeamReviewStatus, PfxRedTeamReviewTemplate, PfxRenderSurfaceKind, PfxRuntimeOptimizationAudit, PfxRuntimeOptimizationAuditEffect, PfxStressScenario, PfxStressScenarioOptions, PfxStyleDifferentiationEffectEvidence, PfxStyleDifferentiationMatrix, PfxStyleDifferentiationVariantEvidence, PfxStyleMaterialTreatment, PfxStyleMotionTreatment, PfxStyleParticleShape, PfxStyleRenderProfile, PfxStyleSilhouette, PfxTaxonomyEffect, PfxTaxonomyEffectReview, PfxTaxonomyReviewBatch, PfxTaxonomyReviewBatchSheet, PfxTaxonomyReviewBatchSheetEffect, PfxTaxonomyReviewBatchSheetIndex, PfxTaxonomyReviewBatchSheetIndexOptions, PfxTaxonomyReviewBatchSheetIndexSheet, PfxTaxonomyReviewBatchSheetOptions, PfxTaxonomyReviewCriterion, PfxTaxonomyReviewCriterionStatus, PfxTaxonomyReviewDossier, PfxTaxonomyReviewDossierEffect, PfxTaxonomyReviewManifestFromSourcesOptions, PfxTaxonomyReviewRankBand, PfxTaxonomyReviewStatus, PfxTaxonomyReviewTemplate, PfxTextureAtlasDescriptor, PfxTextureAtlasSlice, PfxTextureKind, PfxThumbnailAsset, PfxVisualInspectionTargets, SpawnShape } from './types/01'
export type { GamePfxProps, PfxAuthoredRecipe, PfxBlastBurstRuntimeState, PfxChoreographyAudit, PfxChoreographyBeat, PfxComboRingMultiplier, PfxComboRingRuntimeState, PfxDebrisBurstRuntimeState, PfxDropInComponent, PfxDropInComponentProps, PfxDustBurstRuntimeState, PfxEmitterPhysicsFinding, PfxExhaustTelegraphRuntimeState, PfxFlameBurstRuntimeState, PfxFlipbookFrameProps, PfxGlyphTrailRuntimeState, PfxGradientTextureKind, PfxGroupReadinessReport, PfxGroupReadinessRow, PfxHealingGlyphPose, PfxHealingLeafHelixPose, PfxHealingSparklePose, PfxHologramBreakRuntimeState, PfxMarkerReleaseRuntimeState, PfxMeteorBurstRuntimeState, PfxMeteorChunkPose, PfxMobileBenchmarkRow, PfxMobileDeviceBenchmark, PfxParticleColorRamp, PfxParticleEmission, PfxParticleMotionKind, PfxParticleShapeProfile, PfxParticleSimulation, PfxRenderPlan, PfxRenderPlanOptions, PfxRenderSurface, PfxRuntimeResourceCacheStats, PfxScanConeRuntimeState, PfxShockwaveBurstRuntimeState, PfxSpriteVariantLayout, PfxStructuralQualityAudit, PfxStructuralQualityAuditEffect, PfxSurfaceAnimationProps, PfxSurfaceMaterialProps, PfxSurfaceSpatialPolicy, PfxSurfaceTuning, PfxTargetSpawnRuntimeState, PfxThrusterTrailRuntimeState, PfxUiPickupRuntimeState, PfxWarningLoopRuntimeState } from './types/02'
export { PFX_SPRITE_ATLAS_DATA_URI, PFX_SPRITE_SLICES, type PfxSpriteName } from './particleSprites'
export { PFX_FLAME_FLIPBOOK_ATLAS } from './flameFlipbook'
export { PFX_FIREBALL_FLIPBOOK_ATLAS } from './fireballFlipbook'
export { PFX_PLASMA_IMPACT_FLIPBOOK_ATLAS } from './plasmaImpactFlipbook'
export { PFX_MUZZLE_FLASH_ATLAS, type PfxMuzzleFlashAtlasSlice, type PfxMuzzleFlashAtlasSliceName } from './muzzleFlashSprites'

import { clearPfxRuntimeResourceCache } from './constants/04'
import { pfxHotContext } from './constants/07'

if (pfxHotContext) {
  pfxHotContext.accept(() => {
    clearPfxRuntimeResourceCache()
    pfxHotContext.invalidate()
  })
}
