/**
 * GENERATED by scripts/gen-avatar-rig.ts. Do not edit by hand.
 *
 * Source: proofofplay-pirate-nation/3D/pirate/characters-skins/characters-skins-avatar-animation-all-023.glb
 * Source sha256: 0bb6311ee52034a003ed11d5160fb1d09552ccb329b75de6f48ba9db66ad4ee7
 * License: MIT — Copyright (c) 2026 Proof of Play, Inc. (rig data)
 */

export interface RigJoint {
  name: string
  parent: string | null
  translation: readonly number[]
  rotation: readonly number[]
  scale: readonly number[]
  inverseBindMatrix: readonly number[]
  /** Rest world matrix in rig space (glTF axes, column-major). */
  worldMatrix: readonly number[]
}

export const PIRATE_RIG_SOURCE_SHA256 = "0bb6311ee52034a003ed11d5160fb1d09552ccb329b75de6f48ba9db66ad4ee7"

export const PIRATE_RIG: readonly RigJoint[] = [
  {
    "name": "Root",
    "parent": null,
    "translation": [
      0,
      0,
      0
    ],
    "rotation": [
      0,
      0.7071068,
      0,
      0.7071068
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      0,
      0,
      1,
      0,
      0,
      1.0000001,
      0,
      0,
      -1,
      0,
      0,
      0,
      0,
      0,
      0,
      1
    ],
    "worldMatrix": [
      0,
      0,
      -1,
      0,
      0,
      1,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0,
      0,
      1
    ]
  },
  {
    "name": "Body",
    "parent": "Root",
    "translation": [
      0,
      0.16,
      0
    ],
    "rotation": [
      0,
      0,
      0,
      1
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      0,
      0,
      1,
      0,
      0,
      1.0000001,
      0,
      0,
      -1,
      0,
      0,
      0,
      0,
      -0.16,
      0,
      1
    ],
    "worldMatrix": [
      0,
      0,
      -1,
      0,
      0,
      1,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0.16,
      0,
      1
    ]
  },
  {
    "name": "Chest",
    "parent": "Body",
    "translation": [
      0,
      0.06,
      0
    ],
    "rotation": [
      0,
      0,
      0,
      1
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      0,
      0,
      1,
      0,
      0,
      1.0000001,
      0,
      0,
      -1,
      0,
      0,
      0,
      0,
      -0.22,
      0,
      1
    ],
    "worldMatrix": [
      0,
      0,
      -1,
      0,
      0,
      1,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0.22,
      0,
      1
    ]
  },
  {
    "name": "Head",
    "parent": "Chest",
    "translation": [
      0,
      0.14,
      0
    ],
    "rotation": [
      0,
      0,
      0,
      1
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      0,
      0,
      1,
      0,
      0,
      1.0000001,
      0,
      0,
      -1,
      0,
      0,
      0,
      0,
      -0.36,
      0,
      1
    ],
    "worldMatrix": [
      0,
      0,
      -1,
      0,
      0,
      1,
      0,
      0,
      1,
      0,
      0,
      0,
      0,
      0.36,
      0,
      1
    ]
  },
  {
    "name": "Arm.L",
    "parent": "Chest",
    "translation": [
      0.1,
      0.1,
      0
    ],
    "rotation": [
      -0.5000001,
      -0.4999999,
      -0.5000001,
      0.4999999
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      1,
      0,
      -2e-7,
      0,
      2e-7,
      -4e-7,
      1.0000001,
      0,
      0,
      -1.0000001,
      -4e-7,
      0,
      -1e-7,
      -0.0999999,
      -0.32,
      1
    ],
    "worldMatrix": [
      1,
      1e-7,
      2e-7,
      0,
      1e-7,
      -5e-7,
      -1,
      0,
      -1e-7,
      1.0000001,
      -4e-7,
      0,
      0,
      0.32,
      -0.1,
      1
    ]
  },
  {
    "name": "ForeArm.L",
    "parent": "Arm.L",
    "translation": [
      0,
      0.07,
      0
    ],
    "rotation": [
      0,
      0,
      0,
      1
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      1,
      0,
      0,
      0,
      0,
      0,
      1.0000001,
      0,
      0,
      -1.0000001,
      0,
      0,
      0,
      -0.17,
      -0.32,
      1
    ],
    "worldMatrix": [
      1,
      1e-7,
      2e-7,
      0,
      1e-7,
      -5e-7,
      -1,
      0,
      -1e-7,
      1.0000001,
      -4e-7,
      0,
      0,
      0.32,
      -0.17,
      1
    ]
  },
  {
    "name": "Hand.L",
    "parent": "ForeArm.L",
    "translation": [
      0,
      0.07,
      0
    ],
    "rotation": [
      0,
      0,
      0,
      1
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      1,
      0,
      0,
      0,
      0,
      0,
      1.0000001,
      0,
      0,
      -1.0000001,
      0,
      0,
      0,
      -0.24,
      -0.32,
      1
    ],
    "worldMatrix": [
      1,
      1e-7,
      2e-7,
      0,
      1e-7,
      -5e-7,
      -1,
      0,
      -1e-7,
      1.0000001,
      -4e-7,
      0,
      0,
      0.32,
      -0.24,
      1
    ]
  },
  {
    "name": "Arm.R",
    "parent": "Chest",
    "translation": [
      -0.1,
      0.1,
      0
    ],
    "rotation": [
      -0.5000002,
      0.4999999,
      0.5000001,
      0.4999998
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      -1.0000001,
      0,
      -2e-7,
      0,
      -2e-7,
      -4e-7,
      1.0000001,
      0,
      0,
      1.0000002,
      4e-7,
      0,
      1e-7,
      -0.0999999,
      -0.32,
      1
    ],
    "worldMatrix": [
      -0.9999999,
      -2e-7,
      -2e-7,
      0,
      -1e-7,
      -5e-7,
      0.9999999,
      0,
      -1e-7,
      0.9999999,
      5e-7,
      0,
      0,
      0.32,
      0.1,
      1
    ]
  },
  {
    "name": "ForeArm.R",
    "parent": "Arm.R",
    "translation": [
      0,
      0.07,
      0
    ],
    "rotation": [
      0,
      0,
      0,
      1
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      -1.0000001,
      0,
      0,
      0,
      0,
      0,
      1.0000001,
      0,
      0,
      1.0000004,
      0,
      0,
      0,
      -0.17,
      -0.32,
      1
    ],
    "worldMatrix": [
      -0.9999999,
      -2e-7,
      -2e-7,
      0,
      -1e-7,
      -5e-7,
      0.9999999,
      0,
      -1e-7,
      0.9999999,
      5e-7,
      0,
      0,
      0.32,
      0.17,
      1
    ]
  },
  {
    "name": "Hand.R",
    "parent": "ForeArm.R",
    "translation": [
      0,
      0.07,
      0
    ],
    "rotation": [
      0,
      0,
      0,
      1
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      -1.0000001,
      0,
      0,
      0,
      0,
      0,
      1.0000001,
      0,
      0,
      1.0000004,
      0,
      0,
      0,
      -0.2400001,
      -0.32,
      1
    ],
    "worldMatrix": [
      -0.9999999,
      -2e-7,
      -2e-7,
      0,
      -1e-7,
      -5e-7,
      0.9999999,
      0,
      -1e-7,
      0.9999999,
      5e-7,
      0,
      0,
      0.3199999,
      0.24,
      1
    ]
  },
  {
    "name": "Leg.L",
    "parent": "Root",
    "translation": [
      0.05,
      0.16,
      0
    ],
    "rotation": [
      1,
      0,
      -1e-7,
      0
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      -2e-7,
      0,
      -1,
      0,
      0,
      -1.0000001,
      0,
      0,
      -1,
      0,
      2e-7,
      0,
      -0.05,
      0.16,
      0,
      1
    ],
    "worldMatrix": [
      -1e-7,
      0,
      -1,
      0,
      0,
      -1,
      0,
      0,
      -1,
      0,
      1e-7,
      0,
      0,
      0.16,
      -0.05,
      1
    ]
  },
  {
    "name": "LowerLeg.L",
    "parent": "Leg.L",
    "translation": [
      0,
      0.06,
      0
    ],
    "rotation": [
      0,
      0,
      0,
      1
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      -2e-7,
      0,
      -1,
      0,
      0,
      -1.0000001,
      0,
      0,
      -1,
      0,
      2e-7,
      0,
      -0.05,
      0.1,
      0,
      1
    ],
    "worldMatrix": [
      -1e-7,
      0,
      -1,
      0,
      0,
      -1,
      0,
      0,
      -1,
      0,
      1e-7,
      0,
      0,
      0.1,
      -0.05,
      1
    ]
  },
  {
    "name": "Foot.L",
    "parent": "LowerLeg.L",
    "translation": [
      0,
      0.05,
      0
    ],
    "rotation": [
      0,
      0,
      0,
      1
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      -2e-7,
      0,
      -1,
      0,
      0,
      -1.0000001,
      0,
      0,
      -1,
      0,
      2e-7,
      0,
      -0.05,
      0.05,
      0,
      1
    ],
    "worldMatrix": [
      -1e-7,
      0,
      -1,
      0,
      0,
      -1,
      0,
      0,
      -1,
      0,
      1e-7,
      0,
      0,
      0.05,
      -0.05,
      1
    ]
  },
  {
    "name": "Leg.R",
    "parent": "Root",
    "translation": [
      -0.05,
      0.16,
      0
    ],
    "rotation": [
      1,
      0,
      -1e-7,
      0
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      -2e-7,
      0,
      -1,
      0,
      0,
      -1.0000001,
      0,
      0,
      -1,
      0,
      2e-7,
      0,
      0.05,
      0.16,
      0,
      1
    ],
    "worldMatrix": [
      -1e-7,
      0,
      -1,
      0,
      0,
      -1,
      0,
      0,
      -1,
      0,
      1e-7,
      0,
      0,
      0.16,
      0.05,
      1
    ]
  },
  {
    "name": "LowerLeg.R",
    "parent": "Leg.R",
    "translation": [
      0,
      0.06,
      0
    ],
    "rotation": [
      0,
      0,
      0,
      1
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      -2e-7,
      0,
      -1,
      0,
      0,
      -1.0000001,
      0,
      0,
      -1,
      0,
      2e-7,
      0,
      0.05,
      0.1,
      0,
      1
    ],
    "worldMatrix": [
      -1e-7,
      0,
      -1,
      0,
      0,
      -1,
      0,
      0,
      -1,
      0,
      1e-7,
      0,
      0,
      0.1,
      0.05,
      1
    ]
  },
  {
    "name": "Foot.R",
    "parent": "LowerLeg.R",
    "translation": [
      0,
      0.05,
      0
    ],
    "rotation": [
      0,
      0,
      0,
      1
    ],
    "scale": [
      1,
      1,
      1
    ],
    "inverseBindMatrix": [
      -2e-7,
      0,
      -1,
      0,
      0,
      -1.0000001,
      0,
      0,
      -1,
      0,
      2e-7,
      0,
      0.05,
      0.05,
      0,
      1
    ],
    "worldMatrix": [
      -1e-7,
      0,
      -1,
      0,
      0,
      -1,
      0,
      0,
      -1,
      0,
      1e-7,
      0,
      0,
      0.05,
      0.05,
      1
    ]
  }
]

export const PIRATE_JOINT_NAMES: readonly string[] = PIRATE_RIG.map((joint) => joint.name)
