/**
 * GENERATED FILE. Do not edit by hand.
 *
 * Source: https://github.com/proofofplay/piratenation-game
 * Commit: dc921b650c8a1d7c449b2a3553949d3e7c8266e9
 * License: MIT — Copyright (c) 2026 Proof of Play, Inc.
 *
 * Regenerate with:
 *   node --import tsx tools/asset-pirate-nation/scripts/build-avatar-catalog.ts
 */

export const AVATAR_MODEL_PATH = "runtime/models/characters-skins/characters-skins-avatar-animation-all-023.glb" as const

export const AVATAR_SLOTS = ["species","face","eyebrow","hair","facialhair","ears","eyewear","headwear","tops","bottoms","shoes","back"] as const

export type AvatarSlot = (typeof AVATAR_SLOTS)[number]

export type TintChannel = 'skin' | 'hair'

export interface AvatarPartEntry {
  nodeName: string
  index: number
  /** Colors the part follows. Empty when its texture is fixed. */
  tints: readonly TintChannel[]
}

/** Bone order of the shared rig every part binds to. */
export const AVATAR_JOINTS = ["Root","Body","Chest","Head","Arm.L","ForeArm.L","Hand.L","Arm.R","ForeArm.R","Hand.R","Leg.L","LowerLeg.L","Foot.L","Leg.R","LowerLeg.R","Foot.R"] as const

/** Animation clips the art file ships. */
export const AVATAR_ANIMATIONS = ["00_TPose","01_Idle_1","02_Idle_2","03_Idle_3","04_Walk","05_Run","06_Jump_Run","07_Jump_Stand","08_Action_One-Handed_Low","09_Action_One-Handed_Mid","10_Action_One-Handed_High","11_Action_Two-Handed_Low","12_Action_Two-Handed_Mid","13_Action_Two-Handed_High","14_Action_Chopping","15_Waving_Right","16_Waving_Left","17_Two-Handed_Wave","18_Success_Celebration","19_Suprised_Scared","20_Dance_1","21_Dance_2","22_Drunk","23_Kick_Sand","24_Pushups","25_Jumpingjacks","26_Looking_Horizon","27_Dance_3_Backspin","28_Dance_4_Robot","29_Dance_5_Cabbage_Patch","30_Treading_Water","31_Swimming"] as const

export type AvatarAnimationName = (typeof AVATAR_ANIMATIONS)[number]

/** Base body node. It is always present and is never a slot choice. */
export const AVATAR_BASE_NODE = "model" as const

export const AVATAR_PARTS: Record<AvatarSlot, readonly AvatarPartEntry[]> = {
  species: [
    { nodeName: "species 1", index: 1, tints: ["skin"] },
    { nodeName: "species 2", index: 2, tints: ["skin"] },
    { nodeName: "species 3", index: 3, tints: ["hair"] },
    { nodeName: "species 4", index: 4, tints: ["skin","hair"] },
    { nodeName: "species 5", index: 5, tints: [] },
    { nodeName: "species 6", index: 6, tints: [] },
    { nodeName: "species 7", index: 7, tints: [] },
    { nodeName: "species 8", index: 8, tints: ["skin","hair"] },
    { nodeName: "species 9", index: 9, tints: ["skin","hair"] },
    { nodeName: "species 10", index: 10, tints: [] },
    { nodeName: "species 11", index: 11, tints: ["skin"] },
    { nodeName: "species 12", index: 12, tints: [] },
    { nodeName: "species 13", index: 13, tints: [] },
    { nodeName: "species 14", index: 14, tints: [] },
    { nodeName: "species 15", index: 15, tints: [] },
    { nodeName: "species 16", index: 16, tints: [] },
    { nodeName: "species 17", index: 17, tints: [] },
    { nodeName: "species 18", index: 18, tints: [] },
    { nodeName: "species 19", index: 19, tints: [] },
  ],
  face: [
    { nodeName: "face 1", index: 1, tints: [] },
    { nodeName: "face 2", index: 2, tints: ["hair"] },
    { nodeName: "face 3", index: 3, tints: [] },
    { nodeName: "face 4", index: 4, tints: [] },
    { nodeName: "face 5", index: 5, tints: ["hair"] },
    { nodeName: "face 6", index: 6, tints: [] },
    { nodeName: "face 7", index: 7, tints: [] },
    { nodeName: "face 8", index: 8, tints: [] },
    { nodeName: "face 9", index: 9, tints: [] },
    { nodeName: "face 10", index: 10, tints: [] },
    { nodeName: "face 11", index: 11, tints: [] },
    { nodeName: "face 12", index: 12, tints: [] },
    { nodeName: "face 13", index: 13, tints: [] },
    { nodeName: "face 14", index: 14, tints: [] },
    { nodeName: "face 15", index: 15, tints: ["hair"] },
    { nodeName: "face 16", index: 16, tints: [] },
    { nodeName: "face 17", index: 17, tints: [] },
    { nodeName: "face 18", index: 18, tints: [] },
    { nodeName: "face 19", index: 19, tints: [] },
    { nodeName: "face 20", index: 20, tints: [] },
  ],
  eyebrow: [
    { nodeName: "eyebrow 1", index: 1, tints: ["hair"] },
    { nodeName: "eyebrow 2", index: 2, tints: [] },
    { nodeName: "eyebrow 3", index: 3, tints: ["hair"] },
    { nodeName: "eyebrow 4", index: 4, tints: ["hair"] },
    { nodeName: "eyebrow 5", index: 5, tints: [] },
    { nodeName: "eyebrow 6", index: 6, tints: ["hair"] },
    { nodeName: "eyebrow 7", index: 7, tints: ["hair"] },
    { nodeName: "eyebrow 8", index: 8, tints: ["hair"] },
    { nodeName: "eyebrow 9", index: 9, tints: ["hair"] },
    { nodeName: "eyebrow 10", index: 10, tints: ["hair"] },
    { nodeName: "eyebrow 11", index: 11, tints: ["hair"] },
    { nodeName: "eyebrow 12", index: 12, tints: ["hair"] },
    { nodeName: "eyebrow 13", index: 13, tints: ["hair"] },
    { nodeName: "eyebrow 14", index: 14, tints: ["hair"] },
    { nodeName: "eyebrow 15", index: 15, tints: [] },
    { nodeName: "eyebrow 19", index: 19, tints: ["hair"] },
    { nodeName: "eyebrow 20", index: 20, tints: ["hair"] },
  ],
  hair: [
    { nodeName: "hair 1", index: 1, tints: ["hair"] },
    { nodeName: "hair 2", index: 2, tints: ["hair"] },
    { nodeName: "hair 3", index: 3, tints: ["hair"] },
    { nodeName: "hair 4", index: 4, tints: ["hair"] },
    { nodeName: "hair 5", index: 5, tints: ["hair"] },
    { nodeName: "hair 6", index: 6, tints: ["hair"] },
    { nodeName: "hair 7", index: 7, tints: ["hair"] },
    { nodeName: "hair 8", index: 8, tints: ["hair"] },
    { nodeName: "hair 9", index: 9, tints: ["hair"] },
    { nodeName: "hair 10", index: 10, tints: ["hair"] },
    { nodeName: "hair 11", index: 11, tints: [] },
    { nodeName: "hair 12", index: 12, tints: [] },
    { nodeName: "hair 13", index: 13, tints: ["hair"] },
    { nodeName: "hair 14", index: 14, tints: ["hair"] },
    { nodeName: "hair 15", index: 15, tints: ["hair"] },
    { nodeName: "hair 16", index: 16, tints: [] },
    { nodeName: "hair 17", index: 17, tints: [] },
    { nodeName: "hair 18", index: 18, tints: [] },
    { nodeName: "hair 19", index: 19, tints: [] },
    { nodeName: "hair 20", index: 20, tints: [] },
    { nodeName: "hair 21", index: 21, tints: [] },
    { nodeName: "hair 22", index: 22, tints: [] },
    { nodeName: "hair 23", index: 23, tints: [] },
    { nodeName: "hair 24", index: 24, tints: [] },
    { nodeName: "hair 25", index: 25, tints: [] },
    { nodeName: "hair 26", index: 26, tints: [] },
    { nodeName: "hair 27", index: 27, tints: [] },
    { nodeName: "hair 28", index: 28, tints: [] },
    { nodeName: "hair 29", index: 29, tints: [] },
  ],
  facialhair: [
    { nodeName: "facialhair 1", index: 1, tints: ["hair"] },
    { nodeName: "facialhair 2", index: 2, tints: ["hair"] },
    { nodeName: "facialhair 3", index: 3, tints: ["hair"] },
    { nodeName: "facialhair 4", index: 4, tints: ["hair"] },
    { nodeName: "facialhair 5", index: 5, tints: ["hair"] },
    { nodeName: "facialhair 6", index: 6, tints: ["hair"] },
    { nodeName: "facialhair 7", index: 7, tints: ["hair"] },
    { nodeName: "facialhair 8", index: 8, tints: ["hair"] },
    { nodeName: "facialhair 9", index: 9, tints: ["hair"] },
    { nodeName: "facialhair 10", index: 10, tints: ["hair"] },
    { nodeName: "facialhair 11", index: 11, tints: ["hair"] },
    { nodeName: "facialhair 12", index: 12, tints: [] },
    { nodeName: "facialhair 13", index: 13, tints: ["hair"] },
    { nodeName: "facialhair 14", index: 14, tints: [] },
    { nodeName: "facialhair 15", index: 15, tints: [] },
    { nodeName: "facialhair 16", index: 16, tints: [] },
    { nodeName: "facialhair 17", index: 17, tints: [] },
    { nodeName: "facialhair 18", index: 18, tints: [] },
  ],
  ears: [
    { nodeName: "ears 1", index: 1, tints: ["skin"] },
    { nodeName: "ears 2", index: 2, tints: [] },
    { nodeName: "ears 3", index: 3, tints: [] },
    { nodeName: "ears 4", index: 4, tints: [] },
    { nodeName: "ears 5", index: 5, tints: [] },
  ],
  eyewear: [
    { nodeName: "eyewear 1", index: 1, tints: [] },
    { nodeName: "eyewear 2", index: 2, tints: [] },
    { nodeName: "eyewear 3", index: 3, tints: [] },
    { nodeName: "eyewear 4", index: 4, tints: [] },
    { nodeName: "eyewear 5", index: 5, tints: [] },
    { nodeName: "eyewear 6", index: 6, tints: [] },
    { nodeName: "eyewear 7", index: 7, tints: [] },
    { nodeName: "eyewear 8", index: 8, tints: [] },
    { nodeName: "eyewear 9", index: 9, tints: [] },
    { nodeName: "eyewear 10", index: 10, tints: [] },
    { nodeName: "eyewear 11", index: 11, tints: [] },
    { nodeName: "eyewear 12", index: 12, tints: [] },
    { nodeName: "eyewear 13", index: 13, tints: [] },
    { nodeName: "eyewear 14", index: 14, tints: [] },
    { nodeName: "eyewear 15", index: 15, tints: [] },
    { nodeName: "eyewear 16", index: 16, tints: [] },
    { nodeName: "eyewear 17", index: 17, tints: [] },
    { nodeName: "eyewear 18", index: 18, tints: [] },
    { nodeName: "eyewear 19", index: 19, tints: [] },
    { nodeName: "eyewear 20", index: 20, tints: [] },
    { nodeName: "eyewear 21", index: 21, tints: [] },
    { nodeName: "eyewear 22", index: 22, tints: [] },
    { nodeName: "eyewear 23", index: 23, tints: [] },
  ],
  headwear: [
    { nodeName: "headwear 1", index: 1, tints: [] },
    { nodeName: "headwear 2", index: 2, tints: [] },
    { nodeName: "headwear 3", index: 3, tints: [] },
    { nodeName: "headwear 4", index: 4, tints: [] },
    { nodeName: "headwear 5", index: 5, tints: [] },
    { nodeName: "headwear 6", index: 6, tints: [] },
    { nodeName: "headwear 7", index: 7, tints: [] },
    { nodeName: "headwear 8", index: 8, tints: [] },
    { nodeName: "headwear 9", index: 9, tints: [] },
    { nodeName: "headwear 10", index: 10, tints: [] },
    { nodeName: "headwear 11", index: 11, tints: [] },
    { nodeName: "headwear 12", index: 12, tints: [] },
    { nodeName: "headwear 13", index: 13, tints: [] },
    { nodeName: "headwear 14", index: 14, tints: [] },
    { nodeName: "headwear 15", index: 15, tints: [] },
    { nodeName: "headwear 16", index: 16, tints: [] },
    { nodeName: "headwear 17", index: 17, tints: [] },
    { nodeName: "headwear 18", index: 18, tints: [] },
    { nodeName: "headwear 19", index: 19, tints: [] },
    { nodeName: "headwear 20", index: 20, tints: [] },
    { nodeName: "headwear 21", index: 21, tints: [] },
    { nodeName: "headwear 22", index: 22, tints: [] },
    { nodeName: "headwear 23", index: 23, tints: [] },
    { nodeName: "headwear 24", index: 24, tints: [] },
    { nodeName: "headwear 25", index: 25, tints: [] },
    { nodeName: "headwear 26", index: 26, tints: [] },
    { nodeName: "headwear 27", index: 27, tints: [] },
    { nodeName: "headwear 28", index: 28, tints: [] },
    { nodeName: "headwear 29", index: 29, tints: [] },
    { nodeName: "headwear 30", index: 30, tints: [] },
    { nodeName: "headwear 31", index: 31, tints: [] },
    { nodeName: "headwear 32", index: 32, tints: [] },
    { nodeName: "headwear 33", index: 33, tints: [] },
    { nodeName: "headwear 34", index: 34, tints: [] },
    { nodeName: "headwear 35", index: 35, tints: [] },
    { nodeName: "headwear 36", index: 36, tints: [] },
    { nodeName: "headwear 37", index: 37, tints: [] },
    { nodeName: "headwear 38", index: 38, tints: [] },
    { nodeName: "headwear 39", index: 39, tints: [] },
    { nodeName: "headwear 40", index: 40, tints: [] },
    { nodeName: "headwear 41", index: 41, tints: [] },
    { nodeName: "headwear 42", index: 42, tints: [] },
    { nodeName: "headwear 43", index: 43, tints: [] },
    { nodeName: "headwear 44", index: 44, tints: [] },
    { nodeName: "headwear 45", index: 45, tints: [] },
    { nodeName: "headwear 46", index: 46, tints: [] },
    { nodeName: "headwear 47", index: 47, tints: [] },
    { nodeName: "headwear 48", index: 48, tints: [] },
    { nodeName: "headwear 49", index: 49, tints: [] },
    { nodeName: "headwear 50", index: 50, tints: [] },
    { nodeName: "headwear 51", index: 51, tints: [] },
    { nodeName: "headwear 52", index: 52, tints: [] },
    { nodeName: "headwear 53", index: 53, tints: [] },
    { nodeName: "headwear 54", index: 54, tints: [] },
    { nodeName: "headwear 55", index: 55, tints: [] },
    { nodeName: "headwear 56", index: 56, tints: [] },
    { nodeName: "headwear 57", index: 57, tints: [] },
    { nodeName: "headwear 58", index: 58, tints: [] },
    { nodeName: "headwear 59", index: 59, tints: [] },
    { nodeName: "headwear 60", index: 60, tints: [] },
    { nodeName: "headwear 61", index: 61, tints: [] },
    { nodeName: "headwear 62", index: 62, tints: [] },
    { nodeName: "headwear 63", index: 63, tints: [] },
    { nodeName: "headwear 64", index: 64, tints: [] },
    { nodeName: "headwear 65", index: 65, tints: [] },
    { nodeName: "headwear 66", index: 66, tints: [] },
    { nodeName: "headwear 67", index: 67, tints: [] },
    { nodeName: "headwear 68", index: 68, tints: [] },
    { nodeName: "headwear 69", index: 69, tints: [] },
    { nodeName: "headwear 70", index: 70, tints: [] },
    { nodeName: "headwear 71", index: 71, tints: [] },
    { nodeName: "headwear 72", index: 72, tints: [] },
  ],
  tops: [
    { nodeName: "tops 1", index: 1, tints: [] },
    { nodeName: "tops 2", index: 2, tints: [] },
    { nodeName: "tops 3", index: 3, tints: [] },
    { nodeName: "tops 4", index: 4, tints: [] },
    { nodeName: "tops 5", index: 5, tints: [] },
    { nodeName: "tops 6", index: 6, tints: [] },
    { nodeName: "tops 7", index: 7, tints: [] },
    { nodeName: "tops 8", index: 8, tints: [] },
    { nodeName: "tops 9", index: 9, tints: [] },
    { nodeName: "tops 10", index: 10, tints: [] },
    { nodeName: "tops 11", index: 11, tints: [] },
    { nodeName: "tops 12", index: 12, tints: [] },
    { nodeName: "tops 13", index: 13, tints: [] },
    { nodeName: "tops 14", index: 14, tints: [] },
    { nodeName: "tops 15", index: 15, tints: [] },
    { nodeName: "tops 16", index: 16, tints: [] },
    { nodeName: "tops 17", index: 17, tints: [] },
    { nodeName: "tops 18", index: 18, tints: [] },
    { nodeName: "tops 19", index: 19, tints: [] },
    { nodeName: "tops 20", index: 20, tints: [] },
    { nodeName: "tops 21", index: 21, tints: [] },
    { nodeName: "tops 22", index: 22, tints: [] },
    { nodeName: "tops 23", index: 23, tints: [] },
    { nodeName: "tops 24", index: 24, tints: [] },
    { nodeName: "tops 25", index: 25, tints: [] },
    { nodeName: "tops 26", index: 26, tints: [] },
    { nodeName: "tops 27", index: 27, tints: [] },
    { nodeName: "tops 28", index: 28, tints: [] },
    { nodeName: "tops 29", index: 29, tints: [] },
    { nodeName: "tops 30", index: 30, tints: [] },
    { nodeName: "tops 31", index: 31, tints: [] },
    { nodeName: "tops 32", index: 32, tints: [] },
    { nodeName: "tops 33", index: 33, tints: [] },
    { nodeName: "tops 34", index: 34, tints: [] },
    { nodeName: "tops 35", index: 35, tints: [] },
    { nodeName: "tops 36", index: 36, tints: [] },
    { nodeName: "tops 37", index: 37, tints: [] },
    { nodeName: "tops 38", index: 38, tints: [] },
    { nodeName: "tops 39", index: 39, tints: [] },
    { nodeName: "tops 40", index: 40, tints: [] },
    { nodeName: "tops 41", index: 41, tints: [] },
    { nodeName: "tops 42", index: 42, tints: [] },
    { nodeName: "tops 43", index: 43, tints: [] },
    { nodeName: "tops 44", index: 44, tints: [] },
    { nodeName: "tops 45", index: 45, tints: [] },
    { nodeName: "tops 46", index: 46, tints: [] },
    { nodeName: "tops 47", index: 47, tints: [] },
    { nodeName: "tops 48", index: 48, tints: [] },
    { nodeName: "tops 49", index: 49, tints: [] },
    { nodeName: "tops 50", index: 50, tints: [] },
    { nodeName: "tops 51", index: 51, tints: [] },
    { nodeName: "tops 52", index: 52, tints: [] },
    { nodeName: "tops 53", index: 53, tints: [] },
    { nodeName: "tops 54", index: 54, tints: [] },
    { nodeName: "tops 55", index: 55, tints: [] },
    { nodeName: "tops 56", index: 56, tints: [] },
    { nodeName: "tops 57", index: 57, tints: [] },
    { nodeName: "tops 58", index: 58, tints: [] },
    { nodeName: "tops 59", index: 59, tints: [] },
    { nodeName: "tops 60", index: 60, tints: [] },
    { nodeName: "tops 61", index: 61, tints: [] },
    { nodeName: "tops 62", index: 62, tints: [] },
    { nodeName: "tops 63", index: 63, tints: [] },
    { nodeName: "tops 64", index: 64, tints: [] },
    { nodeName: "tops 65", index: 65, tints: [] },
    { nodeName: "tops 66", index: 66, tints: [] },
    { nodeName: "tops 67", index: 67, tints: [] },
    { nodeName: "tops 68", index: 68, tints: [] },
    { nodeName: "tops 69", index: 69, tints: [] },
    { nodeName: "tops 70", index: 70, tints: [] },
    { nodeName: "tops 71", index: 71, tints: [] },
    { nodeName: "tops 72", index: 72, tints: [] },
    { nodeName: "tops 73", index: 73, tints: [] },
    { nodeName: "tops 74", index: 74, tints: [] },
    { nodeName: "tops 75", index: 75, tints: [] },
    { nodeName: "tops 76", index: 76, tints: [] },
    { nodeName: "tops 77", index: 77, tints: [] },
    { nodeName: "tops 78", index: 78, tints: [] },
    { nodeName: "tops 79", index: 79, tints: [] },
    { nodeName: "tops 80", index: 80, tints: [] },
    { nodeName: "tops 81", index: 81, tints: [] },
    { nodeName: "tops 82", index: 82, tints: [] },
  ],
  bottoms: [
    { nodeName: "bottoms 1", index: 1, tints: [] },
    { nodeName: "bottoms 2", index: 2, tints: [] },
    { nodeName: "bottoms 3", index: 3, tints: [] },
    { nodeName: "bottoms 4", index: 4, tints: [] },
    { nodeName: "bottoms 5", index: 5, tints: [] },
    { nodeName: "bottoms 6", index: 6, tints: [] },
    { nodeName: "bottoms 7", index: 7, tints: [] },
    { nodeName: "bottoms 8", index: 8, tints: [] },
    { nodeName: "bottoms 9", index: 9, tints: [] },
    { nodeName: "bottoms 10", index: 10, tints: [] },
    { nodeName: "bottoms 11", index: 11, tints: [] },
    { nodeName: "bottoms 12", index: 12, tints: [] },
    { nodeName: "bottoms 13", index: 13, tints: [] },
    { nodeName: "bottoms 14", index: 14, tints: [] },
    { nodeName: "bottoms 15", index: 15, tints: [] },
    { nodeName: "bottoms 16", index: 16, tints: [] },
    { nodeName: "bottoms 17", index: 17, tints: [] },
    { nodeName: "bottoms 18", index: 18, tints: [] },
    { nodeName: "bottoms 19", index: 19, tints: [] },
    { nodeName: "bottoms 20", index: 20, tints: [] },
    { nodeName: "bottoms 21", index: 21, tints: [] },
    { nodeName: "bottoms 22", index: 22, tints: [] },
    { nodeName: "bottoms 23", index: 23, tints: [] },
  ],
  shoes: [
    { nodeName: "shoes 1", index: 1, tints: [] },
    { nodeName: "shoes 2", index: 2, tints: [] },
    { nodeName: "shoes 3", index: 3, tints: [] },
    { nodeName: "shoes 4", index: 4, tints: [] },
    { nodeName: "shoes 5", index: 5, tints: [] },
    { nodeName: "shoes 6", index: 6, tints: [] },
    { nodeName: "shoes 7", index: 7, tints: [] },
    { nodeName: "shoes 8", index: 8, tints: [] },
    { nodeName: "shoes 9", index: 9, tints: [] },
    { nodeName: "shoes 10", index: 10, tints: [] },
    { nodeName: "shoes 11", index: 11, tints: [] },
    { nodeName: "shoes 12", index: 12, tints: [] },
    { nodeName: "shoes 13", index: 13, tints: [] },
    { nodeName: "shoes 14", index: 14, tints: [] },
    { nodeName: "shoes 15", index: 15, tints: [] },
  ],
  back: [
    { nodeName: "back 1", index: 1, tints: [] },
    { nodeName: "back 2", index: 2, tints: [] },
    { nodeName: "back 3", index: 3, tints: [] },
  ],
}
