import * as THREE from 'three'
import { roundMetric } from '../constants/03'
import { PFX_DUST_BURST_FRAGMENT, PFX_DUST_BURST_VERTEX } from '../constants/06'
import type { PfxDustBurstRuntimeState } from '../types/02'

export function createPfxDustBurstLifecycle(cycle: number): { progress: number; opacity: number; compression: number; roll: number; loft: number; settle: number; stage: 'contact' | 'roll' | 'settle' } {
  const progress = THREE.MathUtils.clamp(cycle, 0, 1)
  if (progress < 0.12) { const contact = progress / 0.12; return { progress, opacity: roundMetric(0.72 + contact * 0.28), compression: roundMetric(1 - contact), roll: 0, loft: 0, settle: 0, stage: 'contact' } }
  if (progress < 0.68) { const release = (progress - 0.12) / 0.56; return { progress, opacity: 1, compression: 0, roll: roundMetric(release), loft: roundMetric(Math.min(1, release * 1.35)), settle: 0, stage: 'roll' } }
  const tail = (progress - 0.68) / 0.32; return { progress, opacity: Math.max(0, roundMetric(1 - Math.pow(tail, 0.76))), compression: 0, roll: 1, loft: 1, settle: roundMetric(tail), stage: 'settle' }
}

export function createPfxDustBurstRuntimeState(elapsedSeconds: number, timing: number, lifetime: number, tempo: number, motionMultiplier: number, target?: PfxDustBurstRuntimeState): PfxDustBurstRuntimeState {
  const rate = Math.max(.05, timing) * Math.max(.1, tempo) * Math.max(.1, motionMultiplier); const periodSeconds = 1.35 * Math.max(.25, lifetime); const cycle = roundMetric(THREE.MathUtils.clamp((Math.max(0, elapsedSeconds) * rate) / periodSeconds, 0, 1)); const lifecycle = createPfxDustBurstLifecycle(cycle)
  const state = target ?? { cycle: 0, periodSeconds: 0, progress: 0, opacity: 0, compression: 0, roll: 0, loft: 0, settle: 0, stage: 'contact' }; Object.assign(state, lifecycle, { cycle, periodSeconds }); return state
}

export function createPfxDustBurstMaterial(opacity: number, colorA: THREE.ColorRepresentation='#b99764', colorB: THREE.ColorRepresentation='#e2c99b', density=.66, styleEdgeHardness=.22): THREE.ShaderMaterial {
  const primary=new THREE.Color(colorA); const secondary=new THREE.Color(colorB); const material=new THREE.ShaderMaterial({uniforms:{uOpacity:{value:THREE.MathUtils.clamp(opacity,0,1)},uProgress:{value:0},uCompression:{value:1},uRoll:{value:0},uLoft:{value:0},uSettle:{value:0},uDensity:{value:THREE.MathUtils.clamp(density,.05,1)},uStyleEdgeHardness:{value:THREE.MathUtils.clamp(styleEdgeHardness,0,1)},uColorA:{value:new THREE.Vector3(primary.r,primary.g,primary.b)},uColorB:{value:new THREE.Vector3(secondary.r,secondary.g,secondary.b)}},transparent:false,blending:THREE.NormalBlending,depthWrite:true,depthTest:true,side:THREE.DoubleSide,toneMapped:false,vertexShader:PFX_DUST_BURST_VERTEX,fragmentShader:PFX_DUST_BURST_FRAGMENT})
  material.userData['pfxDustBurstMaterial']=true; material.userData['pfxDustBurstDrawCalls']=1; material.userData['pfxDustBurstParticleCount']=0; material.userData['pfxDustBurstFragmentTextureSamples']=0; material.userData['pfxDustBurstTransientAllocationsPerFrame']=0; material.userData['pfxDustBurstMeshJustification']='grounded-radial-pigment-crown-with-integrated-contact-core-roll-lobes-skirt-and-grit'; return material
}

export function createPfxDustBurstGeometry(): THREE.BufferGeometry {
  const positions:number[]=[]; const normals:number[]=[]; const parts:number[]=[]; const origins:number[]=[]; const directions:number[]=[]; const seeds:number[]=[]; const point=new THREE.Vector3(); const normal=new THREE.Vector3(); const quaternion=new THREE.Quaternion(); const scaleVector=new THREE.Vector3(); const matrix=new THREE.Matrix4(); const normalMatrix=new THREE.Matrix3()
  const append=(source:THREE.BufferGeometry,origin:[number,number,number],scale:[number,number,number],rotation:[number,number,number],direction:[number,number,number],part:number,seed:number)=>{const geometry=source.index?source.toNonIndexed():source; quaternion.setFromEuler(new THREE.Euler(...rotation)); scaleVector.set(...scale); matrix.compose(new THREE.Vector3(...origin),quaternion,scaleVector);normalMatrix.getNormalMatrix(matrix);const attribute=geometry.getAttribute('position');const normalAttribute=geometry.getAttribute('normal');for(let index=0;index<attribute.count;index+=1){point.fromBufferAttribute(attribute,index).applyMatrix4(matrix);normal.fromBufferAttribute(normalAttribute,index).applyMatrix3(normalMatrix).normalize();positions.push(point.x,point.y,point.z);normals.push(normal.x,normal.y,normal.z);parts.push(part);origins.push(...origin);directions.push(...direction);seeds.push(seed)}if(geometry!==source)geometry.dispose();source.dispose()}
  append(new THREE.SphereGeometry(1,8,5),[0,.08,0],[.42,.14,.42],[0,0,0],[0,1,0],0,.03)
  const lobeCount=12
  for(let index=0;index<lobeCount;index+=1){const angle=(index/lobeCount)*Math.PI*2+(index%2)*.13;const outer=index%3!==0;const radius=outer?.66+(index%2)*.13:.14+(index%2)*.06;const direction:[number,number,number]=[Math.cos(angle),.1+((index+1)%3)*.04,Math.sin(angle)];const origin:[number,number,number]=[Math.cos(angle)*radius,.1+(index%5)*.05,Math.sin(angle)*radius];append(new THREE.SphereGeometry(1,8,5),origin,[.25+(index%3)*.035,.17+(index%4)*.022,.22+((index+1)%3)*.034],[index*.09,-angle*.14,index*.055],direction,1,.05+((index*5)%lobeCount)*.07)}
  const skirtCount=10
  for(let index=0;index<skirtCount;index+=1){const angle=(index/skirtCount)*Math.PI*2+.14;const direction:[number,number,number]=[Math.cos(angle),.025,Math.sin(angle)];const origin:[number,number,number]=[Math.cos(angle)*1.08,.025,Math.sin(angle)*1.08];append(new THREE.BoxGeometry(.34,.035,.1),origin,[1,1,1],[0,-angle+Math.PI/2,(index%2?.06:-.04)],direction,2,.08+((index*3)%skirtCount)*.085)}
  const gritDirections:Array<[number,number,number]>=[[1,.42,.22],[-1,.34,-.18],[.2,.58,1],[-.24,.48,-1],[.72,.3,.76],[-.78,.26,-.68],[.64,.52,-.72],[-.6,.46,.82]]
  gritDirections.forEach((direction,index)=>{const d=new THREE.Vector3(...direction).normalize();const origin:[number,number,number]=[d.x*.58,d.y*.22+.08,d.z*.58];append(new THREE.TetrahedronGeometry(1,0),origin,[.045,.075,.045],[index*.31,index*.19,-index*.13],direction,3,.1+((index*3)%8)*.1)})
  const geometry=new THREE.BufferGeometry();geometry.setAttribute('position',new THREE.Float32BufferAttribute(positions,3));geometry.setAttribute('normal',new THREE.Float32BufferAttribute(normals,3));geometry.setAttribute('aDustPart',new THREE.Float32BufferAttribute(parts,1));geometry.setAttribute('aDustOrigin',new THREE.Float32BufferAttribute(origins,3));geometry.setAttribute('aDustDirection',new THREE.Float32BufferAttribute(directions,3));geometry.setAttribute('aDustSeed',new THREE.Float32BufferAttribute(seeds,1));geometry.computeBoundingBox();geometry.computeBoundingSphere();geometry.userData['pfxDustBurstGeometry']=true;geometry.userData['pfxDustBurstClosedComponents']=true;geometry.userData['pfxDustBurstContactCoreCount']=1;geometry.userData['pfxDustBurstRollLobeCount']=12;geometry.userData['pfxDustBurstGroundSkirtCount']=10;geometry.userData['pfxDustBurstGritChipCount']=8;geometry.userData['pfxDustBurstConnectedComponents']=31;geometry.userData['pfxDustBurstTriangles']=positions.length/9;geometry.userData['pfxDustBurstDrawCalls']=1;return geometry
}
