import type { BurgerShopEmitter, BurgerShopRecipe } from '../burger-shop/types'
import type { PfxTaxonomyEffect } from '../types/01'

const constant = (value: number) => ({ min: value, max: value })
const range = (min: number, max: number) => ({ min, max })
const unityUp: [number, number, number] = [-90, 0, 0]
const shrink: { t: number; v: number }[] = [
  { t: 0, v: 1 },
  { t: 1, v: 0 },
]
const grow: { t: number; v: number }[] = [
  { t: 0, v: 0.3 },
  { t: 0.75, v: 1 },
  { t: 1, v: 1 },
]
const pop: { t: number; v: number }[] = [
  { t: 0, v: 0.72 },
  { t: 1, v: 1 },
]
const snowSize: { t: number; v: number }[] = [
  { t: 0, v: 0 },
  { t: 0.135, v: 0.93 },
  { t: 1, v: 0 },
]
const holdThenDie: { t: number; v: number }[] = [
  { t: 0, v: 1 },
  { t: 0.78, v: 1 },
  { t: 1, v: 0 },
]
const twinkle: { t: number; v: number }[] = [
  { t: 0, v: 1 },
  { t: 0.16, v: 0.72 },
  { t: 0.3, v: 0.91 },
  { t: 0.49, v: 0.55 },
  { t: 0.65, v: 0.69 },
  { t: 0.77, v: 0.25 },
  { t: 0.91, v: 0.38 },
  { t: 1, v: 0 },
]
const confettiColors = [
  [1, 0, 0.52, 1],
  [0.91, 1, 0, 1],
  [0.18, 0.83, 0.04, 1],
  [0, 0.91, 1, 1],
  [1, 0.5, 0.19, 1],
  [0.83, 0, 1, 1],
]

export type PirateEffectType = PfxTaxonomyEffect['effectType']
export type PirateRole = PfxTaxonomyEffect['role']

export interface PirateRecipe extends BurgerShopRecipe {
  effectType: PirateEffectType
  role: PirateRole
}

function statusRecipe(
  id: string,
  label: string,
  sourcePrefab: string,
  iconTexture: string,
  splashColor: number[],
  ringColor: number[],
): PirateRecipe {
  return {
    id,
    label,
    sourcePrefab,
    duration: 2,
    looping: false,
    effectType: 'status',
    role: 'burst',
    emitters: [
      {
        name: 'WaterSplashes',
        texture: 'glow',
        sheet: { columns: 1, rows: 1 },
        billboard: 'camera',
        blend: 'additive',
        duration: 1.5,
        looping: false,
        delay: 0.35,
        life: range(0.5, 0.9),
        speed: range(0.6, 1.4),
        size: range(0.08, 0.16),
        gravity: 0.6,
        rate: 0,
        burst: constant(16),
        shape: { kind: 'hemisphere', radius: 0.32 },
        sizeCurve: shrink,
        color: [splashColor],
        localEuler: unityUp,
        lumaAlpha: false,
      },
      {
        name: 'Icon',
        texture: iconTexture,
        sheet: { columns: 1, rows: 1 },
        billboard: 'vertical',
        blend: 'cutout',
        duration: 2,
        looping: false,
        delay: 0.15,
        life: constant(1.9),
        speed: constant(0),
        size: constant(1.4),
        gravity: 0,
        rate: 0,
        burst: constant(1),
        shape: { kind: 'point' },
        sizeCurve: pop,
        color: [[1, 1, 1, 1]],
        localPosition: [0, 1.7, 0],
        lumaAlpha: false,
      },
      {
        name: 'Box',
        texture: 'soft-circle',
        sheet: { columns: 1, rows: 1 },
        billboard: 'horizontal',
        blend: 'additive',
        duration: 2,
        looping: false,
        delay: 0.2,
        life: constant(1.6),
        speed: constant(0),
        size: constant(1.35),
        gravity: 0,
        rate: 0,
        burst: constant(1),
        shape: { kind: 'point' },
        sizeCurve: grow,
        color: [splashColor],
        localPosition: [0, 0.06, 0],
        lumaAlpha: true,
      },
      {
        name: 'Ring',
        texture: 'soft-circle',
        sheet: { columns: 1, rows: 1 },
        billboard: 'horizontal',
        blend: 'additive',
        duration: 1.4,
        looping: false,
        delay: 0.2,
        life: constant(1.1),
        speed: constant(0),
        size: constant(1.05),
        gravity: 0,
        rate: 0,
        burst: constant(1),
        shape: { kind: 'point' },
        sizeCurve: grow,
        color: [ringColor],
        lumaAlpha: true,
      },
      {
        name: 'BoilingVoxels',
        texture: 'glow',
        sheet: { columns: 1, rows: 1 },
        billboard: 'camera',
        blend: 'additive',
        duration: 0.7,
        looping: false,
        delay: 0.5,
        life: range(1.1, 2),
        speed: constant(0),
        size: range(0.07, 0.14),
        gravity: -0.08,
        rate: 0,
        burst: constant(18),
        shape: { kind: 'hemisphere', radius: 0.22 },
        sizeCurve: twinkle,
        color: [splashColor],
        localEuler: unityUp,
        localPosition: [0, 0.12, 0],
        lumaAlpha: false,
      },
    ],
  }
}

export const PIRATE_RECIPES: PirateRecipe[] = [
  statusRecipe(
    'pirate-status-buff',
    'Pirate Nation status buff',
    'PF_VFX_Status_Buff',
    'status-buff',
    [0.024, 0.455, 1, 1],
    [0, 0.811, 1, 1],
  ),
  statusRecipe(
    'pirate-status-debuff',
    'Pirate Nation status debuff',
    'PF_VFX_Status_Debuff',
    'status-debuff',
    [1, 0.078, 0, 1],
    [1, 0.109, 0, 1],
  ),
  statusRecipe(
    'pirate-status-attack',
    'Pirate Nation status attack',
    'PF_VFX_Status_BuffAttack',
    'status-attack',
    [1, 0.42, 0.05, 1],
    [1, 0.55, 0.08, 1],
  ),
  statusRecipe(
    'pirate-status-heal',
    'Pirate Nation status heal',
    'PF_VFX_Status_Buff_Heal',
    'status-up',
    [0.996, 1, 0.514, 1],
    [0.991, 0.982, 1, 1],
  ),
  {
    id: 'pirate-shield',
    label: 'Pirate Nation shield',
    sourcePrefab: 'Shield',
    duration: 2,
    looping: false,
    effectType: 'shield',
    role: 'burst',
    emitters: [
      {
        name: 'Shield',
        texture: 'shield-fx',
        sheet: { columns: 1, rows: 1 },
        billboard: 'vertical',
        blend: 'additive',
        duration: 2,
        looping: false,
        life: constant(5),
        speed: constant(0),
        size: constant(1.25),
        gravity: 0,
        rate: 0,
        burst: constant(1),
        shape: { kind: 'point' },
        sizeCurve: pop,
        color: [[1, 1, 1, 1]],
        localPosition: [0, 0.95, 0],
        lumaAlpha: false,
      },
    ],
  },
  {
    id: 'pirate-sparkle',
    label: 'Pirate Nation harvest sparkle',
    sourcePrefab: 'SparkleVFX',
    duration: 3,
    looping: true,
    effectType: 'loot',
    role: 'loop',
    emitters: [
      {
        name: 'SparkleVFX',
        texture: 'sparkle',
        sheet: { columns: 1, rows: 1 },
        billboard: 'camera',
        blend: 'additive',
        duration: 3,
        looping: true,
        life: range(1.4, 2.2),
        speed: constant(0),
        size: range(0.45, 0.7),
        gravity: 0,
        rate: 2,
        burst: constant(3),
        shape: { kind: 'box', size: [0.35, 0.55, 0.35] },
        sizeCurve: pop,
        color: [[1, 0.96, 0.62, 1]],
        localPosition: [0, 1.15, 0],
        lumaAlpha: false,
      },
    ],
  },
  {
    id: 'pirate-rain',
    label: 'Pirate Nation combat rain',
    sourcePrefab: 'VFX_Combat_Rain',
    duration: 6,
    looping: true,
    effectType: 'weather',
    role: 'loop',
    emitters: [
      {
        name: 'VFX_Rain',
        texture: 'glow',
        sheet: { columns: 1, rows: 1 },
        billboard: 'camera',
        blend: 'additive',
        duration: 6,
        looping: true,
        life: range(0.8, 1.2),
        speed: constant(0),
        size: range(0.07, 0.12),
        gravity: 0,
        rate: 22,
        shape: { kind: 'box', size: [2.2, 2.4, 2.2] },
        color: [[0, 0.92, 1, 0.85]],
        localPosition: [0, 1.9, 0],
        worldVelocity: [0.18, -1.9, 0],
        lumaAlpha: false,
        noise: range(0.08, 0.2),
      },
      {
        name: 'Splash',
        texture: 'glow',
        sheet: { columns: 1, rows: 1 },
        billboard: 'horizontal',
        blend: 'additive',
        duration: 5,
        looping: true,
        life: range(0.18, 0.3),
        speed: constant(0.2),
        size: range(0.06, 0.12),
        gravity: 0,
        rate: 3,
        burst: constant(3),
        shape: { kind: 'rectangle', size: [1.6, 1.6] },
        sizeCurve: shrink,
        color: [[0.55, 0.9, 1, 0.55]],
        lumaAlpha: false,
      },
    ],
  },
  {
    id: 'pirate-snow',
    label: 'Pirate Nation combat snow',
    sourcePrefab: 'VFX_Combat_Snow',
    duration: 30,
    looping: true,
    effectType: 'weather',
    role: 'loop',
    emitters: [
      {
        name: 'VFX_Combat_Snow',
        texture: 'glow',
        sheet: { columns: 1, rows: 1 },
        billboard: 'camera',
        blend: 'additive',
        duration: 30,
        looping: true,
        life: constant(1),
        speed: constant(0),
        size: constant(0.16),
        gravity: 0,
        rate: 24,
        shape: { kind: 'box', size: [2.4, 2.6, 2.4] },
        sizeCurve: snowSize,
        color: [[1, 1, 1, 1]],
        localPosition: [0, 2.0, 0],
        worldVelocity: [0, -1.1, 0],
        lumaAlpha: false,
        noise: range(0.2, 0.6),
      },
    ],
  },
  {
    id: 'pirate-ash',
    label: 'Pirate Nation combat ash',
    sourcePrefab: 'VFX_Combat_Ash',
    duration: 30,
    looping: true,
    effectType: 'weather',
    role: 'loop',
    emitters: [
      {
        name: 'VFX_Combat_Embers',
        texture: 'glow',
        sheet: { columns: 1, rows: 1 },
        billboard: 'camera',
        blend: 'additive',
        duration: 30,
        looping: true,
        life: range(6, 10),
        speed: constant(0),
        size: constant(0.1),
        gravity: 0,
        rate: 10,
        shape: { kind: 'box', size: [2.0, 2.2, 2.0] },
        color: [[1, 0.35, 0.08, 0.9]],
        localPosition: [0, 1.3, 0],
        worldVelocity: [0.06, 0.22, 0],
        lumaAlpha: false,
        noise: range(0.12, 0.28),
      },
      {
        name: 'VFX_Combat_Ash',
        texture: 'glow',
        sheet: { columns: 1, rows: 1 },
        billboard: 'camera',
        blend: 'additive',
        duration: 30,
        looping: true,
        life: range(1.4, 2.2),
        speed: constant(0),
        size: range(0.08, 0.14),
        gravity: 0,
        rate: 14,
        shape: { kind: 'box', size: [2.0, 2.2, 2.0] },
        sizeCurve: snowSize,
        color: [[0.55, 0.5, 0.46, 0.55]],
        localPosition: [0, 1.3, 0],
        worldVelocity: [0.08, 0.12, 0],
        lumaAlpha: false,
        noise: range(0.1, 0.22),
      },
    ],
  },
  {
    id: 'pirate-clouds',
    label: 'Pirate Nation arena clouds',
    sourcePrefab: 'VFX_CombatArena_Clouds',
    duration: 20,
    looping: true,
    effectType: 'weather',
    role: 'loop',
    emitters: [
      {
        name: 'VFX_CloudRingBillboard',
        texture: 'clouds',
        sheet: { columns: 2, rows: 2 },
        billboard: 'camera',
        blend: 'alpha',
        duration: 12,
        looping: true,
        life: range(8, 12),
        speed: range(0.04, 0.1),
        size: range(1.05, 1.4),
        gravity: 0,
        rate: 0.25,
        burst: constant(3),
        shape: { kind: 'box', size: [1.4, 0.25, 1.4] },
        sheetVariant: true,
        color: [[1, 1, 1, 0.85]],
        localPosition: [0, 1.45, 0],
        lumaAlpha: false,
      },
    ],
  },
  {
    id: 'pirate-disappear',
    label: 'Pirate Nation disappear splash',
    sourcePrefab: 'VFX_Disappear_Ship_Standalone',
    duration: 2,
    looping: false,
    effectType: 'dissolve',
    role: 'burst',
    emitters: [
      {
        name: 'VFX_Disappear_Ship_Standalone',
        texture: 'smoke',
        sheet: { columns: 2, rows: 2 },
        billboard: 'camera',
        blend: 'alpha',
        duration: 2,
        looping: false,
        life: constant(0.8),
        speed: range(0.8, 1.6),
        size: range(0.28, 0.5),
        gravity: 0.4,
        rate: 0,
        burst: constant(10),
        shape: { kind: 'hemisphere', radius: 0.25 },
        sizeCurve: shrink,
        color: [[0.85, 0.88, 0.92, 0.85]],
        localEuler: unityUp,
        lumaAlpha: false,
      },
      {
        name: 'Splash_Smaller_Middle',
        texture: 'glow',
        sheet: { columns: 1, rows: 1 },
        billboard: 'camera',
        blend: 'additive',
        duration: 2,
        looping: false,
        delay: 0.08,
        life: constant(0.55),
        speed: range(0.4, 0.9),
        size: range(0.12, 0.22),
        gravity: 0.3,
        rate: 0,
        burst: constant(6),
        shape: { kind: 'hemisphere', radius: 0.18 },
        sizeCurve: shrink,
        color: [[0.95, 0.97, 1, 0.8]],
        localEuler: unityUp,
        lumaAlpha: false,
      },
    ],
  },
  {
    id: 'pirate-ship-wake',
    label: 'Pirate Nation ship wake',
    sourcePrefab: 'ShipTrail',
    duration: 10.5,
    looping: true,
    effectType: 'trail',
    role: 'loop',
    emitters: [
      {
        name: 'Wake_Stern_Particles',
        texture: 'soft-circle',
        sheet: { columns: 1, rows: 1 },
        billboard: 'horizontal',
        blend: 'additive',
        duration: 10.5,
        looping: true,
        life: constant(2.1),
        speed: constant(0),
        size: constant(0.37),
        gravity: 0,
        rate: 8,
        shape: { kind: 'rectangle', size: [0.4, 1.6] },
        sizeCurve: grow,
        color: [[0.459, 0.91, 0.898, 1]],
        localPosition: [0, 0.05, -0.8],
        lumaAlpha: true,
      },
    ],
  },
  {
    id: 'pirate-confetti',
    label: 'Pirate Nation confetti blast',
    sourcePrefab: 'FastConfettiBlastRainbow',
    duration: 3,
    looping: false,
    effectType: 'ui',
    role: 'burst',
    emitters: [
      {
        name: 'FastConfettiBlastRainbow',
        texture: 'confetti',
        sheet: { columns: 3, rows: 3 },
        billboard: 'camera',
        blend: 'cutout',
        duration: 1,
        looping: false,
        life: constant(1.6),
        speed: range(3.2, 6.5),
        size: range(0.12, 0.2),
        gravity: 0.4,
        rate: 0,
        burst: constant(28),
        shape: { kind: 'cone', angle: 14, radius: 0.2 },
        sizeCurve: holdThenDie,
        rotateOverLife: true,
        sheetVariant: true,
        color: confettiColors,
        localEuler: unityUp,
        localPosition: [0, 1.2, 0],
        lumaAlpha: true,
      },
      {
        name: 'Clouds',
        texture: 'smoke',
        sheet: { columns: 2, rows: 2 },
        billboard: 'camera',
        blend: 'alpha',
        duration: 3,
        looping: false,
        life: constant(1),
        speed: range(1.2, 2.2),
        size: constant(0.28),
        gravity: -0.15,
        rate: 0,
        burst: constant(10),
        shape: { kind: 'sphere', radius: 0.22 },
        sizeCurve: shrink,
        sheetVariant: true,
        color: [[1, 1, 1, 0.7]],
        lumaAlpha: false,
      },
      {
        name: 'Glow',
        texture: 'soft-circle',
        sheet: { columns: 1, rows: 1 },
        billboard: 'camera',
        blend: 'additive',
        duration: 1,
        looping: false,
        life: constant(0.15),
        speed: constant(0),
        size: constant(1.2),
        gravity: 0,
        rate: 0,
        burst: constant(1),
        shape: { kind: 'point' },
        sizeCurve: shrink,
        color: [[1, 1, 1, 0.7]],
        localPosition: [0, 1.0, 0],
        lumaAlpha: true,
      },
    ],
  },
  {
    id: 'pirate-results-smoke',
    label: 'Pirate Nation results smoke',
    sourcePrefab: 'VFX_CombatResults_Smoke',
    duration: 3,
    looping: true,
    effectType: 'smoke',
    role: 'loop',
    emitters: [
      {
        name: 'Emitter',
        texture: 'smoke',
        sheet: { columns: 2, rows: 2 },
        billboard: 'camera',
        blend: 'alpha',
        duration: 3,
        looping: true,
        life: constant(2.2),
        speed: range(0.08, 0.16),
        size: range(0.7, 1.0),
        gravity: -0.06,
        rate: 2,
        shape: { kind: 'cone', angle: 8, radius: 0.12 },
        sheetVariant: true,
        sizeCurve: grow,
        color: [[0.22, 0.22, 0.22, 0.85]],
        localEuler: unityUp,
        localPosition: [0, 0.35, 0],
        minHeight: 0.05,
        lumaAlpha: false,
      },
    ],
  },
  {
    id: 'pirate-godrays',
    label: 'Pirate Nation godrays',
    sourcePrefab: 'vfx_godrays_01',
    duration: 4,
    looping: true,
    effectType: 'ui',
    role: 'loop',
    emitters: [
      {
        name: 'Godrays',
        texture: 'godrays',
        sheet: { columns: 1, rows: 1 },
        billboard: 'horizontal',
        blend: 'additive',
        duration: 4,
        looping: true,
        life: constant(4),
        speed: constant(0),
        size: range(1.8, 2.2),
        gravity: 0,
        rate: 0,
        burst: constant(1),
        shape: { kind: 'point' },
        color: [[1, 0.92, 0.65, 0.55]],
        lumaAlpha: true,
      },
    ],
  },
]

export function getPirateRecipe(id: string): PirateRecipe {
  const recipe = PIRATE_RECIPES.find((entry) => entry.id === id)
  if (!recipe) throw new Error(`Unknown Pirate Nation effect: ${id}`)
  return recipe
}

export const PIRATE_IDS = PIRATE_RECIPES.map((recipe) => recipe.id)

export function isPirateId(id: string): boolean {
  return PIRATE_IDS.includes(id)
}

export type { BurgerShopEmitter }
