import { authoredRecipe } from '../constants/01'

export default authoredRecipe('curse-column', 'Curse column', 'Dark vertical debuff read with restrained overdraw.', [
  { kind: 'beam-column', role: 'body', opacity: 0.98, scale: 1.12, phase: 'curse-column-torment-pillar', tuning: { meshGeometry: 'curse-twisted-spire', meshShader: 'energy-column', meshMotion: 'charge', lifecycle: 'curse-column-binding', widthScale: 12, blend: 'additive', colorOverride: '#8534d4' } },
  { kind: 'magic-circle', role: 'aura', opacity: 0.96, scale: 1.22, phase: 'curse-column-binding-seal', tuning: { meshGeometry: 'curse-binding-seal', meshMotion: 'charge', lifecycle: 'curse-column-binding', blend: 'additive', colorOverride: '#8f4bd8', positionOffset: [0, -0.86, 0] } },
  { kind: 'particles', role: 'aura', opacity: 0.98, scale: 0.98, phase: 'curse-column-orbiting-rune-witnesses', tuning: { motion: 'orbit-ring', sprite: 'rune', blend: 'additive', lifecycle: 'curse-column-binding', colorOverride: '#e9ceff', ramp: 'pinned-hot', death: 'erode', countScale: 1.15, speedScale: 0.54, speedJitter: 0.12, spawnScale: 1.12, depthScale: 2.4, spinScale: 0.22, gravity: 0, turbulenceScale: 0.08, size: [0.32, 0.54, 0.16], positionOffset: [0, 0.14, 0] } },
  { kind: 'particles', role: 'volume', opacity: 0.94, scale: 0.92, phase: 'curse-column-falling-rune-volume', tuning: { motion: 'drift-cloud', sprite: 'rune', blend: 'additive', lifecycle: 'curse-column-binding', colorOverride: '#c483ff', ramp: 'held', death: 'erode', delay: 0.05, window: 0.72, lifeScale: 0.9, countScale: 1, speedScale: 0.38, speedJitter: 0.2, spawnScale: 1.28, depthScale: 2.8, spinScale: 0.18, gravity: -2.2, turbulenceScale: 0.12, size: [0.28, 0.46, 0.14], positionOffset: [0, 0.48, 0] } },
  { kind: 'reward-gem', role: 'body', opacity: 0.96, scale: 0.32, phase: 'curse-column-crown-void', tuning: { meshMotion: 'charge', lifecycle: 'curse-column-binding', blend: 'additive', colorOverride: '#d7a8ff', positionOffset: [0, 0.3, 0] } },
], 2, 1)
