import { authoredRecipe } from '../constants/01'

export default authoredRecipe('debris-release', 'Debris release', 'Particle-first chunky breakup: a seeded irregular hero fan, forward chips, launch streaks, grounded dust, and a counter-scatter resolve.', [
  { kind: 'particles', role: 'impact', opacity: 0.98, scale: 1.16, phase: 'debris-release-hero-rocks', tuning: { motion: 'impact-burst', sprite: 'debris', blend: 'alpha', lifecycle: 'debris-release-ballistic', colorOverride: '#e1b87d', ramp: 'pigment', death: 'erode', ease: 'snap', delay: 0, window: 0.28, lifeScale: 0.72, countScale: 0.44, speedScale: 5.6, speedJitter: 0.68, drag: 0.82, gravity: -2.4, spawnScale: 0.12, depthScale: 3.8, turbulenceScale: 0.06, spinScale: 1.2, stretch: 0.12, randomizeAzimuth: true, impactVector: [-1, 0.5, 0.3], spreadAngle: 0.86, size: [0.2, 0.42, 0.12], positionOffset: [0.2, -0.68, 0] } },
  { kind: 'particles', role: 'impact', opacity: 0.98, scale: 1.1, phase: 'debris-release-forward-chip-fan', tuning: { motion: 'radial-burst', sprite: 'debris', blend: 'alpha', lifecycle: 'debris-release-ballistic', colorOverride: '#dca96a', ramp: 'pigment', death: 'erode', ease: 'snap', delay: 0.16, window: 0.3, lifeScale: 0.9, countScale: 0.6, speedScale: 9.2, speedJitter: 0.58, drag: 0.5, gravity: -4.2, spawnScale: 0.12, depthScale: 3.4, turbulenceScale: 0.04, spinScale: 1.2, stretch: 0.18, randomizeAzimuth: true, impactVector: [-1, 0.5, 0.3], spreadAngle: 0.9, size: [0.16, 0.3, 0.1], positionOffset: [0.14, -0.64, 0] } },
  { kind: 'particles', role: 'impact', opacity: 0.76, scale: 1.2, phase: 'debris-release-launch-streaks', tuning: { motion: 'radial-burst', sprite: 'streak', blend: 'additive', lifecycle: 'debris-release-ballistic', colorOverride: '#e2a15a', ramp: 'pinned-hot', ease: 'snap', delay: 0.38, window: 0.26, lifeScale: 0.8, countScale: 0.52, speedScale: 12.5, speedJitter: 0.5, drag: 0.42, gravity: 0, spawnScale: 0.08, depthScale: 3.2, turbulenceScale: 0, spinScale: 0, stretch: 2.4, randomizeAzimuth: true, impactVector: [-1, 0.52, 0.28], spreadAngle: 0.58, size: [0.18, 0.56, 0.08], positionOffset: [0.16, -0.56, 0] } },
  { kind: 'particles', role: 'volume', opacity: 0.66, scale: 1.5, phase: 'debris-release-ground-dust-sheet', tuning: { motion: 'shockwave-ground-burst', sprite: 'smoke', blend: 'alpha', lifecycle: 'debris-release-ballistic', colorOverride: '#aa8767', ramp: 'pigment', death: 'erode', alphaGamma: 0.92, spriteColorMix: 0.28, delay: 0.58, window: 0.26, lifeScale: 0.95, countScale: 0.5, speedScale: 4.2, speedJitter: 0.42, drag: 1.18, gravity: -0.48, spawnScale: 0.38, spawnLift: 0.04, depthScale: 4.2, turbulenceScale: 0.2, spinScale: 0.42, stretch: 0.08, impactVector: [-1, 0.18, 0.12], spreadAngle: 0.96, size: [0.24, 0.5, 0.34], positionOffset: [0.14, -0.32, 0] } },
  { kind: 'particles', role: 'trail', opacity: 0.78, scale: 0.7, phase: 'debris-release-counter-chips', tuning: { motion: 'radial-burst', sprite: 'debris', blend: 'alpha', lifecycle: 'debris-release-ballistic', colorOverride: '#684d35', ramp: 'dark', death: 'erode', delay: 0.9, window: 0.16, lifeScale: 0.7, countScale: 0.1, speedScale: 5.2, speedJitter: 0.62, drag: 0.62, gravity: -3.6, spawnScale: 0.1, depthScale: 2.8, turbulenceScale: 0.03, spinScale: 1.05, stretch: 0.08, randomizeAzimuth: true, impactVector: [1, 0.25, -0.25], spreadAngle: 0.78, size: [0.1, 0.16, 0.07], positionOffset: [0.12, -0.68, 0] } },
], 2, 1.12)
