import { authoredRecipe } from '../constants/01'

export default authoredRecipe('spawn-telegraph', 'Spawn telegraph', 'A restrained particle-authored boundary acquires the spawn radius, shallow front-and-back trace lanes gather into the spawn locus, and a compact spark contact releases into sparse directional residue.', [
  {
    kind: 'particles',
    role: 'aura',
    opacity: 0.76,
    scale: 1.72,
    phase: 'spawn-telegraph-ground-boundary',
    tuning: {
      motion: 'telegraph-boundary-drift',
      sprite: 'streak',
      blend: 'additive',
      colorOverride: '#72e7ff',
      ramp: 'held',
      ringPurpose: 'boundary',
      lifecycle: 'spawn-telegraph-assembly',
      delay: 0,
      window: 0.24,
      lifeScale: 2,
      countScale: 1.8,
      reducedMotionCountScale: 3.2,
      speedScale: 1,
      speedJitter: 0.22,
      drag: 2.6,
      gravity: 0,
      spawnScale: 1.18,
      depthScale: 1,
      size: [0.08, 0.34, 0.04],
      sizeJitter: 0.42,
      stretch: 0.8,
      spinScale: 0.25,
      alphaGamma: 0.28,
      flicker: 0.3,
      turbulenceScale: 0,
      death: 'erode',
      referenceSource: 'Brackeys-vfx-in-godot-CC0-and-three.quarks-MIT',
      referenceAdaptation: 'one stratified band of conventional streak cards establishes the gameplay radius as an almost continuous annulus with three subtle breathing seams; overlapping varied tangent fragments preserve an authoritative circumference without oversized decorative gaps or endpoint flares, while a modest reduced-motion reserve keeps the same footprint readable without animation, mesh geometry, or stacked rings',
      referenceLicense: 'CC0-1.0-and-MIT',
    },
  },
  {
    kind: 'particles',
    role: 'body',
    opacity: 0.9,
    scale: 2.8,
    phase: 'spawn-telegraph-avatar-materialization',
    tuning: {
      motion: 'materialize-gather',
      sprite: 'trace-variants',
      reducedMotionSprite: 'trace-variants',
      blend: 'additive',
      colorOverride: '#55d6ef',
      ramp: 'held',
      lifecycle: 'spawn-telegraph-assembly',
      delay: 0,
      window: 0.26,
      lifeScale: 2.1,
      countScale: 4.2,
      reducedMotionCountScale: 2.4,
      speedScale: 0.9,
      speedJitter: 0.35,
      drag: 1.5,
      gravity: 0,
      spawnScale: 0.72,
      spawnLift: 0,
      depthScale: 3.2,
      size: [0.035, 0.24, 0.025],
      sizeJitter: 0.9,
      stretch: 1.35,
      spinScale: 0.04,
      alphaGamma: 0.28,
      turbulenceScale: 0.12,
      randomizeAzimuth: false,
      death: 'erode',
      positionOffset: [0, -1.12, 0],
      referenceSource: 'Kenney-Particle-Pack-CC0-and-Brackeys-vfx-in-godot-CC0-and-three.quarks-MIT-and-Effekseer-MIT',
      referenceAdaptation: 'one conventional additive emitter distributes seven CC0 Kenney trace variants through seeded front and back depth lanes and velocity-stretches them along shallow curved paths into a compact spawn locus; varied silhouettes, size, value, lifetime, azimuth, and radial origin keep the actionable gather spatial without resolving a proxy character, cage, flame column, or repeated rack of identical cards; the source reservoir is radius-capped inside the boundary ring so the gameplay footprint stays authoritative',
      referenceLicense: 'CC0-1.0-and-MIT',
    },
  },
  {
    kind: 'particles',
    role: 'volume',
    opacity: 0.84,
    scale: 3.2,
    phase: 'spawn-telegraph-release-wake',
    tuning: {
      motion: 'materialize-release',
      sprite: 'spark',
      reducedMotionSprite: 'spark',
      blend: 'additive',
      colorOverride: '#8eeeff',
      ramp: 'held',
      lifecycle: 'spawn-telegraph-assembly',
      delay: 0.04,
      window: 0.14,
      lifeScale: 2.1,
      countScale: 2.8,
      reducedMotionCountScale: 2,
      speedScale: 1.4,
      speedJitter: 0.45,
      drag: 1.6,
      gravity: 0,
      spawnScale: 1.1,
      spawnLift: 0.02,
      depthScale: 3.2,
      size: [0.05, 0.3, 0.05],
      sizeJitter: 0.95,
      stretch: 0.78,
      spinScale: 0.22,
      alphaGamma: 0.32,
      turbulenceScale: 0.16,
      randomizeAzimuth: false,
      death: 'erode',
      positionOffset: [0, -0.82, 0],
      referenceSource: 'Kenney-Particle-Pack-CC0-and-Brackeys-vfx-in-godot-CC0-and-three.quarks-MIT-and-Effekseer-MIT',
      referenceAdaptation: 'one conventional additive emitter gives the CC0 Kenney spark cell three deterministic cohorts: a compact high-value radial contact declares the exact spawn instant, shorter ground sparks clear the footprint, and a sparse slower upward/outward cohort carries the decay; the gather retires during this handoff so the peak stays brief and hierarchical without smoke stamps, a solid proxy, or a fourth draw call',
      referenceLicense: 'CC0-1.0-and-MIT',
    },
  },
], 2, 0.86)
