import { authoredRecipe } from '../constants/01'

export default authoredRecipe(
  'teleport-telegraph',
  'Teleport telegraph',
  'A particle-authored destination boundary brackets opposed depth streams that compress into a phase-lock plane, then releases a sparse upward afterimage wake.',
  [
    {
      kind: 'particles',
      role: 'aura',
      opacity: 0.76,
      scale: 1.66,
      phase: 'teleport-telegraph-ground-boundary',
      tuning: {
        motion: 'telegraph-boundary-drift',
        sprite: 'streak',
        reducedMotionSprite: 'streak',
        blend: 'additive',
        colorOverride: '#42cfff',
        ramp: 'held',
        ringPurpose: 'boundary',
        delay: 0,
        window: 0.34,
        lifeScale: 0.95,
        countScale: 1.85,
        reducedMotionCountScale: 2.2,
        speedScale: 0.72,
        speedJitter: 0.24,
        drag: 2.4,
        gravity: 0,
        spawnScale: 1.08,
        depthScale: 1,
        size: [0.055, 0.24, 0.035],
        sizeJitter: 0.58,
        stretch: 0.72,
        spinScale: 0.18,
        alphaGamma: 0.26,
        flicker: 0.24,
        turbulenceScale: 0,
        death: 'erode',
        referenceSource: 'Brackeys-vfx-in-godot-and-three.quarks-and-marinho-godot-visual-effects',
        referenceAdaptation: 'one conventional streak-card emitter establishes an almost continuous gameplay boundary with seeded tangent motion and restrained inward support currents; it replaces the opaque torus and crystal pylons while retaining an honest destination footprint from every review camera',
        referenceLicense: 'CC0-1.0-and-MIT',
      },
    },
    {
      kind: 'particles',
      role: 'body',
      opacity: 0.84,
      scale: 1.82,
      phase: 'teleport-telegraph-phase-convergence',
      tuning: {
        motion: 'phase-transfer-column',
        sprite: 'trace-variants',
        reducedMotionSprite: 'trace-variants',
        blend: 'additive',
        colorOverride: '#65dcff',
        ramp: 'held',
        death: 'erode',
        delay: 0,
        window: 0.5,
        lifeScale: 0.84,
        countScale: 3.3,
        reducedMotionCountScale: 2,
        speedScale: 0.82,
        speedJitter: 0.28,
        drag: 1.45,
        spawnScale: 0.82,
        depthScale: 3,
        turbulenceScale: 0.1,
        gravity: 0,
        spinScale: 0.12,
        size: [0.05, 0.25, 0.06],
        sizeJitter: 0.46,
        stretch: 0.75,
        alphaGamma: 0.44,
        flicker: 0.16,
        positionOffset: [0, -0.48, 0],
        referenceSource: 'Kenney-Particle-Pack-CC0-and-Godot-Shaders-CC0-teleport-effect-and-Brackeys-vfx-in-godot-and-three.quarks',
        referenceAdaptation: 'seven depth-distributed populations of CC0 Kenney trace variants counter-rotate from above and below into a narrow phase-lock plane, adapting the CC0 teleport dissolve-edge idea into a wider destination-focused transfer with visible inward trajectories, varied filament silhouettes, and no proxy body, crystal mesh, or flat portal card',
        referenceLicense: 'CC0-1.0-and-MIT',
      },
    },
    {
      kind: 'particles',
      role: 'volume',
      opacity: 0.24,
      scale: 1.7,
      phase: 'teleport-telegraph-phase-veil',
      tuning: {
        motion: 'phase-transfer-column',
        sprite: 'smoke-variants',
        reducedMotionSprite: 'smoke-variants',
        blend: 'alpha',
        colorOverride: '#3ca6cf',
        ramp: 'held',
        death: 'erode',
        delay: 0,
        window: 0.56,
        lifeScale: 1.05,
        countScale: 2.2,
        reducedMotionCountScale: 1.6,
        speedScale: 0.55,
        speedJitter: 0.35,
        drag: 1.6,
        spawnScale: 0.74,
        depthScale: 3.2,
        turbulenceScale: 0.18,
        gravity: 0,
        spinScale: 0.55,
        size: [0.13, 0.24, 0.18],
        sizeJitter: 0.62,
        stretch: 0.12,
        alphaGamma: 0.55,
        flicker: 0.08,
        positionOffset: [0, -0.48, 0],
        referenceSource: 'Kenney-Particle-Pack-CC0-and-Godot-Shaders-CC0-teleport-effect-and-marinho-godot-visual-effects-and-three.quarks',
        referenceAdaptation: 'eight varied CC0 smoke cards form a restrained translucent phase veil along the opposed transfer lanes, adding conventional particle depth and a readable material handoff behind the sharp traces without an opaque proxy body or mesh shell',
        referenceLicense: 'CC0-1.0-and-MIT',
      },
    },
    {
      kind: 'particles',
      role: 'volume',
      opacity: 0.44,
      scale: 1.6,
      phase: 'teleport-telegraph-transfer-wake',
      tuning: {
        motion: 'column-rise',
        sprite: 'streak',
        reducedMotionSprite: 'streak',
        blend: 'additive',
        colorOverride: '#78bfff',
        ramp: 'held',
        death: 'erode',
        delay: 0.22,
        window: 0.5,
        lifeScale: 1,
        countScale: 1.25,
        reducedMotionCountScale: 0.72,
        speedScale: 1,
        speedJitter: 0.38,
        drag: 1.35,
        spawnScale: 0.66,
        depthScale: 2.8,
        turbulenceScale: 0.16,
        gravity: 0,
        spinScale: 0.18,
        size: [0.01, 0.085, 0.01],
        sizeJitter: 0.58,
        stretch: 1.35,
        alphaGamma: 0.7,
        flicker: 0.12,
        positionOffset: [0, -0.46, 0],
        referenceSource: 'Brackeys-vfx-in-godot-and-Effekseer-and-marinho-godot-visual-effects',
        referenceAdaptation: 'a restrained population of thin conventional streak particles begins rising through real depth before the gather peaks, carrying the same blue phase energy into a continuous afterimage column instead of appearing later as disconnected white chevrons or abruptly dark geometry',
        referenceLicense: 'CC0-1.0-and-MIT',
      },
    },
  ],
  2,
  0.72,
)
