import { authoredRecipe } from '../constants/01'

export default authoredRecipe(
  'warp-telegraph',
  'Warp telegraph',
  'A particle-authored boundary and an inward-drifting countdown pool frame the destination while a tall single-chirality vortex and a soft refraction veil fold space around a bright vertical lock core, then close through a compact particle lock.',
  [
    {
      kind: 'particles',
      role: 'aura',
      opacity: 1,
      scale: 1.68,
      phase: 'warp-telegraph-ground-boundary',
      tuning: {
        motion: 'telegraph-boundary-drift',
        sprite: 'streak',
        reducedMotionSprite: 'streak',
        blend: 'additive',
        colorOverride: '#3fb8ff',
        ramp: 'held',
        ringPurpose: 'boundary',
        delay: 0,
        window: 0.42,
        lifeScale: 1.1,
        countScale: 3.6,
        reducedMotionCountScale: 2.4,
        speedScale: 0.72,
        speedJitter: 0.22,
        drag: 2.5,
        gravity: 0,
        spawnScale: 1.1,
        depthScale: 1,
        size: [0.05, 0.18, 0.04],
        sizeJitter: 0.58,
        stretch: 0.76,
        spinScale: 0.16,
        alphaGamma: 0.28,
        flicker: 0.2,
        turbulenceScale: 0,
        death: 'erode',
        referenceSource: 'Brackeys-vfx-in-godot-and-three.quarks-and-Bevy-Hanabi-and-Effekseer',
        referenceAdaptation: 'one evenly stratified band of conventional streak cards owns the warning radius at full onset strength while short tangent travel and an eroding retirement keep the circumference alive without a torus, filled disc, or second decorative ring',
        referenceLicense: 'CC0-1.0-and-MIT',
      },
    },
    {
      kind: 'particles',
      role: 'aura',
      opacity: 0.38,
      scale: 0.98,
      phase: 'warp-telegraph-interior-pool',
      tuning: {
        motion: 'converge-center',
        sprite: 'glow',
        reducedMotionSprite: 'glow',
        blend: 'additive',
        colorOverride: '#2f9fd8',
        ramp: 'held',
        delay: 0,
        window: 0.5,
        lifeScale: 1.2,
        countScale: 2.6,
        reducedMotionCountScale: 1.6,
        speedScale: 0.5,
        speedJitter: 0.2,
        drag: 2.2,
        gravity: 0,
        spawnScale: 0.9,
        depthScale: 1,
        size: [0.12, 0.3, 0.12],
        sizeJitter: 0.5,
        stretch: 0.1,
        spinScale: 0.08,
        alphaGamma: 0.5,
        flicker: 0.32,
        turbulenceScale: 0,
        death: 'erode',
        referenceSource: 'Brackeys-vfx-in-godot-and-three.quarks-and-Bevy-Hanabi',
        referenceAdaptation: 'a soft procedural glow pool drifts inward across the ground plane inside the boundary, giving the telegraph the inner fill and gathering countdown cue reviewers found missing without an opaque disc or a second ring',
        referenceLicense: 'CC0-1.0-and-MIT',
      },
    },
    {
      kind: 'particles',
      role: 'body',
      opacity: 0.94,
      scale: 1.5,
      phase: 'warp-telegraph-folding-ribbons',
      tuning: {
        motion: 'warp-vortex',
        sprite: 'spark',
        reducedMotionSprite: 'spark',
        blend: 'additive',
        colorOverride: '#78e3ff',
        ramp: 'held',
        delay: 0,
        window: 0.32,
        lifeScale: 1.08,
        countScale: 4.6,
        reducedMotionCountScale: 1.3,
        speedScale: 2.4,
        speedJitter: 0.34,
        drag: 1.35,
        gravity: 0,
        spawnScale: 1.22,
        depthScale: 5.2,
        size: [0.045, 0.17, 0.045],
        sizeJitter: 0.55,
        stretch: 0.55,
        spinScale: 0.12,
        alphaGamma: 0.32,
        flicker: 0.14,
        turbulenceScale: 0.05,
        death: 'erode',
        positionOffset: [0, -0.08, 0],
        referenceSource: 'Kenney-Particle-Pack-and-Brackeys-vfx-in-godot-and-three.quarks-and-Bevy-Hanabi',
        referenceAdaptation: 'fine CC0 Kenney spark cards ride a tall single-chirality inward spiral funnel with per-particle phase, radius, height, and tightness variance at a calmer readable speed, forming one continuous volumetric vortex column without the mirrored bowtie lanes, hollow center, or hair-thin chaotic scribble rejected in review',
        referenceLicense: 'CC0-1.0-and-MIT',
      },
    },
    {
      kind: 'particles',
      role: 'volume',
      opacity: 0.2,
      scale: 1.42,
      phase: 'warp-telegraph-refraction-veil',
      tuning: {
        motion: 'warp-vortex',
        sprite: 'smoke-variants',
        reducedMotionSprite: 'smoke-variants',
        blend: 'alpha',
        colorOverride: '#2a7fae',
        ramp: 'held',
        delay: 0.02,
        window: 0.4,
        lifeScale: 1.28,
        countScale: 3.4,
        reducedMotionCountScale: 1.1,
        speedScale: 2.6,
        speedJitter: 0.4,
        drag: 1.8,
        gravity: 0,
        spawnScale: 1.15,
        depthScale: 5.2,
        size: [0.09, 0.22, 0.14],
        sizeJitter: 0.9,
        stretch: 0.14,
        spinScale: 0.85,
        alphaGamma: 0.68,
        flicker: 0.06,
        turbulenceScale: 0.14,
        death: 'erode',
        positionOffset: [0, -0.07, 0],
        referenceSource: 'Kenney-Particle-Pack-and-Godot-MIT-particle-demos-and-marinho-godot-visual-effects',
        referenceAdaptation: 'eight varied CC0 smoke cards follow the same single-chirality spiral funnel at lower speed and value, filling the center with restrained translucent refraction depth and a soft retirement without an opaque disc or proxy volume',
        referenceLicense: 'CC0-1.0-and-MIT',
      },
    },
    {
      kind: 'particles',
      role: 'body',
      opacity: 0.8,
      scale: 0.9,
      phase: 'warp-telegraph-lock-core',
      tuning: {
        motion: 'column-rise',
        sprite: 'glow',
        reducedMotionSprite: 'glow',
        blend: 'additive',
        colorOverride: '#aeeaff',
        ramp: 'held',
        delay: 0.08,
        window: 0.4,
        lifeScale: 1.15,
        countScale: 2.2,
        reducedMotionCountScale: 1.2,
        speedScale: 0.55,
        speedJitter: 0.18,
        drag: 1.2,
        gravity: 0,
        spawnScale: 0.5,
        depthScale: 0.8,
        size: [0.05, 0.22, 0.05],
        sizeJitter: 0.5,
        stretch: 0.35,
        spinScale: 0.1,
        alphaGamma: 0.35,
        flicker: 0.18,
        turbulenceScale: 0.04,
        death: 'erode',
        positionOffset: [0, -0.05, 0],
        referenceSource: 'Brackeys-vfx-in-godot-and-three.quarks-and-Bevy-Hanabi-and-Effekseer',
        referenceAdaptation: 'a narrow column of soft procedural glow motes rises through the ring center, anchoring the visual hierarchy with the bright vertical beam motif reviewers asked for as the warp-arrival signature without a mesh beam or billboard card',
        referenceLicense: 'CC0-1.0-and-MIT',
      },
    },
    {
      kind: 'particles',
      role: 'impact',
      opacity: 0.86,
      scale: 1.45,
      phase: 'warp-telegraph-release-shear',
      tuning: {
        motion: 'spherical-converge',
        sprite: 'spark',
        reducedMotionSprite: 'spark',
        blend: 'additive',
        colorOverride: '#c0f5ff',
        ramp: 'held',
        delay: 0.32,
        window: 0.26,
        lifeScale: 1.3,
        countScale: 3.3,
        reducedMotionCountScale: 0.6,
        speedScale: 0.72,
        speedJitter: 0.42,
        drag: 1.9,
        gravity: -0.05,
        spawnScale: 1.1,
        depthScale: 4.2,
        size: [0.024, 0.1, 0.024],
        sizeJitter: 0.9,
        stretch: 1.5,
        spinScale: 0.18,
        alphaGamma: 0.28,
        flicker: 0.16,
        turbulenceScale: 0.08,
        death: 'erode',
        positionOffset: [0, -0.12, 0],
        referenceSource: 'Kenney-Particle-Pack-and-Brackeys-vfx-in-godot-and-Effekseer',
        referenceAdaptation: 'a delayed spherical set of fine velocity-stretched CC0 Kenney sparks folds through three depth-bearing feeder lanes into the same destination, creating a compact bright peak and staggered retirement without an outward impact splash, broad rectangular cards, or a mesh shockwave ring',
        referenceLicense: 'CC0-1.0-and-MIT',
      },
    },
  ],
  2,
  0.86,
)
