import type { UiSkinIconName } from '../types'

export interface UiSkinIconCatalogEntry {
  name: UiSkinIconName
  label: string
}

export const UI_SKIN_ICON_CATALOG: readonly UiSkinIconCatalogEntry[] = [
  { name: 'home', label: 'Home' },
  { name: 'coin', label: 'Coins' },
  { name: 'gem', label: 'Gems' },
  { name: 'heart', label: 'Heart' },
  { name: 'star', label: 'Star' },
  { name: 'sparkles', label: 'Sparkles' },
  { name: 'flame', label: 'Flame' },
  { name: 'play', label: 'Play' },
  { name: 'shield', label: 'Shield' },
  { name: 'sword', label: 'Sword' },
  { name: 'skull', label: 'Skull' },
  { name: 'trophy', label: 'Trophy' },
  { name: 'gift', label: 'Gift' },
  { name: 'bag', label: 'Bag' },
  { name: 'shop', label: 'Shop' },
  { name: 'cards', label: 'Cards' },
  { name: 'package', label: 'Package' },
  { name: 'lock', label: 'Lock' },
  { name: 'unlock', label: 'Unlock' },
  { name: 'check', label: 'Check' },
  { name: 'close', label: 'Close' },
  { name: 'back', label: 'Back' },
  { name: 'info', label: 'Info' },
  { name: 'question', label: 'Question' },
  { name: 'warning', label: 'Warning' },
  { name: 'success', label: 'Success' },
  { name: 'error', label: 'Error' },
  { name: 'mail', label: 'Mail' },
  { name: 'chat', label: 'Chat' },
  { name: 'search', label: 'Search' },
  { name: 'megaphone', label: 'Megaphone' },
  { name: 'settings', label: 'Settings' },
  { name: 'gamepad', label: 'Gamepad' },
  { name: 'clock', label: 'Clock' },
  { name: 'rank-1', label: 'Rank 1' },
  { name: 'rank-2', label: 'Rank 2' },
  { name: 'rank-3', label: 'Rank 3' },
  { name: 'crown', label: 'Crown' },
] as const

export const UI_SKIN_ICON_DEMO_NAMES: readonly UiSkinIconName[] = [
  'home',
  'search',
  'mail',
  'chat',
  'shop',
  'coin',
  'gem',
  'cards',
  'gift',
  'star',
  'trophy',
  'rank-1',
  'crown',
  'heart',
  'flame',
  'shield',
  'sword',
  'play',
  'settings',
  'lock',
] as const
