import type { ComponentType } from 'react'
import {
  ArrowCounterClockwise,
  ArrowLeft,
  ArrowSquareOut,
  Bell,
  Cards,
  ChatCircleDots,
  Check,
  CheckCircle,
  Clock,
  Coins,
  Copy,
  Diamond,
  Envelope,
  Eraser,
  Flame,
  GameController,
  Gear,
  Gift,
  Heart,
  ArrowClockwise,
  House,
  Info,
  Link,
  Lock,
  LockOpen,
  MagnifyingGlass,
  Megaphone,
  NumberCircleOne,
  NumberCircleThree,
  NumberCircleTwo,
  Package,
  PencilSimple,
  Play,
  Plus,
  Question,
  Shield,
  ShoppingBagOpen,
  Skull,
  Sparkle,
  Star,
  Sword,
  Trophy,
  User,
  Users,
  Warning,
  X,
  XCircle,
} from '@phosphor-icons/react'
import { adaptUiSkinExternalIcon, createUiSkinIconPack } from './runtime'

function phosphorIcon<Props extends Record<string, unknown>>(Component: ComponentType<Props>) {
  return adaptUiSkinExternalIcon(Component, {
    extraProps: {
      weight: 'duotone',
    } as unknown as Partial<Props>,
  })
}

const PHOSPHOR_STYLE_ICON_COMPONENTS = {
  home: phosphorIcon(House),
  coin: phosphorIcon(Coins),
  gem: phosphorIcon(Diamond),
  heart: phosphorIcon(Heart),
  star: phosphorIcon(Star),
  sparkles: phosphorIcon(Sparkle),
  flame: phosphorIcon(Flame),
  play: phosphorIcon(Play),
  shield: phosphorIcon(Shield),
  sword: phosphorIcon(Sword),
  skull: phosphorIcon(Skull),
  trophy: phosphorIcon(Trophy),
  gift: phosphorIcon(Gift),
  bag: phosphorIcon(ShoppingBagOpen),
  shop: phosphorIcon(ShoppingBagOpen),
  cards: phosphorIcon(Cards),
  package: phosphorIcon(Package),
  lock: phosphorIcon(Lock),
  unlock: phosphorIcon(LockOpen),
  check: phosphorIcon(Check),
  close: phosphorIcon(X),
  back: phosphorIcon(ArrowLeft),
  info: phosphorIcon(Info),
  question: phosphorIcon(Question),
  warning: phosphorIcon(Warning),
  success: phosphorIcon(CheckCircle),
  error: phosphorIcon(XCircle),
  mail: phosphorIcon(Envelope),
  chat: phosphorIcon(ChatCircleDots),
  search: phosphorIcon(MagnifyingGlass),
  megaphone: phosphorIcon(Megaphone),
  settings: phosphorIcon(Gear),
  gamepad: phosphorIcon(GameController),
  clock: phosphorIcon(Clock),
  'rank-1': phosphorIcon(NumberCircleOne),
  'rank-2': phosphorIcon(NumberCircleTwo),
  'rank-3': phosphorIcon(NumberCircleThree),
  // New icons (added for PRD-referenced lucide names)
  plus: phosphorIcon(Plus),
  share: phosphorIcon(ArrowSquareOut),
  copy: phosphorIcon(Copy),
  undo: phosphorIcon(ArrowCounterClockwise),
  redo: phosphorIcon(ArrowClockwise),
  pencil: phosphorIcon(PencilSimple),
  eraser: phosphorIcon(Eraser),
  link: phosphorIcon(Link),
  user: phosphorIcon(User),
  users: phosphorIcon(Users),
  help: phosphorIcon(Question),
  alert: phosphorIcon(Bell),
} as const

export const phosphorUiSkinIconPack = createUiSkinIconPack({
  id: 'phosphor',
  label: 'Phosphor',
  icons: PHOSPHOR_STYLE_ICON_COMPONENTS,
})
