import type { ComponentType } from 'react'
import {
  IconAlertCircle,
  IconAlertTriangle,
  IconArrowLeft,
  IconCards,
  IconCheck,
  IconCircleCheck,
  IconClock,
  IconCoins,
  IconCrown,
  IconDiamond,
  IconDeviceGamepad2,
  IconFlame,
  IconGift,
  IconHeart,
  IconHelpCircle,
  IconHome2,
  IconInfoCircle,
  IconLock,
  IconLockOpen,
  IconMail,
  IconMessageCircle,
  IconNumber1,
  IconNumber2,
  IconNumber3,
  IconPackage,
  IconPlayerPlay,
  IconSearch,
  IconSettings,
  IconShield,
  IconShoppingBag,
  IconSkull,
  IconSparkles,
  IconStar,
  IconSword,
  IconTrophy,
  IconX,
} from '@tabler/icons-react'
import { adaptUiSkinExternalIcon, createUiSkinIconPack } from './runtime'

function tablerIcon<Props extends Record<string, unknown>>(Component: ComponentType<Props>) {
  return adaptUiSkinExternalIcon(Component, {
    extraProps: {
      stroke: 1.9,
    } as unknown as Partial<Props>,
  })
}

const TABLER_STYLE_ICON_COMPONENTS = {
  home: tablerIcon(IconHome2),
  coin: tablerIcon(IconCoins),
  gem: tablerIcon(IconDiamond),
  heart: tablerIcon(IconHeart),
  star: tablerIcon(IconStar),
  sparkles: tablerIcon(IconSparkles),
  flame: tablerIcon(IconFlame),
  play: tablerIcon(IconPlayerPlay),
  shield: tablerIcon(IconShield),
  sword: tablerIcon(IconSword),
  skull: tablerIcon(IconSkull),
  trophy: tablerIcon(IconTrophy),
  gift: tablerIcon(IconGift),
  bag: tablerIcon(IconShoppingBag),
  shop: tablerIcon(IconShoppingBag),
  cards: tablerIcon(IconCards),
  package: tablerIcon(IconPackage),
  lock: tablerIcon(IconLock),
  unlock: tablerIcon(IconLockOpen),
  check: tablerIcon(IconCheck),
  close: tablerIcon(IconX),
  back: tablerIcon(IconArrowLeft),
  info: tablerIcon(IconInfoCircle),
  question: tablerIcon(IconHelpCircle),
  warning: tablerIcon(IconAlertTriangle),
  success: tablerIcon(IconCircleCheck),
  error: tablerIcon(IconAlertCircle),
  mail: tablerIcon(IconMail),
  chat: tablerIcon(IconMessageCircle),
  search: tablerIcon(IconSearch),
  settings: tablerIcon(IconSettings),
  gamepad: tablerIcon(IconDeviceGamepad2),
  clock: tablerIcon(IconClock),
  'rank-1': tablerIcon(IconNumber1),
  'rank-2': tablerIcon(IconNumber2),
  'rank-3': tablerIcon(IconNumber3),
  crown: tablerIcon(IconCrown),
} as const

export const tablerUiSkinIconPack = createUiSkinIconPack({
  id: 'tabler',
  label: 'Tabler',
  icons: TABLER_STYLE_ICON_COMPONENTS,
})
