// Generated by scripts/prepare-patient.py from the actual body surface.
export const PATIENT_LAYOUT = {
  floorY: -0.9,
  eyes: [0, -0.25, -0.50],
  wound: [0, -0.673708, 0.080000],
  care: [0.15, -0.669708, 0.080000],
  beam: [0, -0.609277, -0.10],
  beamGripY: -0.489277,
} as const;
