/**
 * Writes `contracts/avatarRig.generated.ts` from the Pirate Nation avatar GLB:
 * joint order, local rest TRS and inverse bind matrices of the shared rig.
 * The validator and the showcase rig guards compare against this data.
 *
 * Usage: npm run gen:rig
 */
import { createHash } from 'node:crypto'
import { readFileSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { createIo } from '../src/gltfIo'
import { PIRATE_AVATAR_GLB, pirateModelsDir, TOOL_ROOT } from '../src/paths'

const round = (values: ArrayLike<number>) => Array.from(values, (v) => Math.round(v * 1e7) / 1e7)

async function main(): Promise<void> {
  const path = join(pirateModelsDir(), PIRATE_AVATAR_GLB)
  const bytes = readFileSync(path)
  const doc = await createIo().readBinary(new Uint8Array(bytes))
  const skins = doc.getRoot().listSkins()
  const skin = skins[0]
  if (!skin) throw new Error(`${path}: no skin`)
  const joints = skin.listJoints()
  const ibm = skin.getInverseBindMatrices()?.getArray()
  if (!ibm || ibm.length !== joints.length * 16) throw new Error(`${path}: bad inverse bind matrices`)

  const rig = joints.map((joint, i) => ({
    name: joint.getName(),
    parent: joints.find((candidate) => candidate.listChildren().includes(joint))?.getName() ?? null,
    translation: round(joint.getTranslation()),
    rotation: round(joint.getRotation()),
    scale: round(joint.getScale()),
    inverseBindMatrix: round(ibm.slice(i * 16, i * 16 + 16)),
    worldMatrix: round(joint.getWorldMatrix()),
  }))
  const sha = createHash('sha256').update(bytes).digest('hex')
  const out = `/**
 * GENERATED by scripts/gen-avatar-rig.ts. Do not edit by hand.
 *
 * Source: proofofplay-pirate-nation/3D/pirate/${PIRATE_AVATAR_GLB}
 * Source sha256: ${sha}
 * License: MIT — Copyright (c) 2026 Proof of Play, Inc. (rig data)
 */

export interface RigJoint {
  name: string
  parent: string | null
  translation: readonly number[]
  rotation: readonly number[]
  scale: readonly number[]
  inverseBindMatrix: readonly number[]
  /** Rest world matrix in rig space (glTF axes, column-major). */
  worldMatrix: readonly number[]
}

export const PIRATE_RIG_SOURCE_SHA256 = ${JSON.stringify(sha)}

export const PIRATE_RIG: readonly RigJoint[] = ${JSON.stringify(rig, null, 2)}

export const PIRATE_JOINT_NAMES: readonly string[] = PIRATE_RIG.map((joint) => joint.name)
`
  writeFileSync(join(TOOL_ROOT, 'contracts/avatarRig.generated.ts'), out)
  // The Blender side reads the same data as JSON.
  writeFileSync(
    join(TOOL_ROOT, 'contracts/data/rig.generated.json'),
    JSON.stringify({ sourceSha256: sha, joints: rig.map(({ name, parent, worldMatrix }) => ({ name, parent, worldMatrix })) }, null, 1) + '\n',
  )
  console.log(`wrote ${rig.length} joints: ${rig.map((j) => j.name).join(', ')}`)
}

main().catch((error: unknown) => {
  console.error(error)
  process.exit(1)
})
